;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 25/11/2020 17:54:20
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2932			GOTO	_main
$05A6	$	_mul_32x32_u:
$05A6	$1303			BCF	STATUS, RP1
$05A7	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$05A8	$3022			MOVLW	34
;math.ppas,1579 :: 		
$05A9	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$05AA	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$05AB	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$05AC	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$05AD	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$05AE	$	_NEXT:
;math.ppas,1589 :: 		
$05AE	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$05AF	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$05B0	$2DDC			GOTO	_EXIT2
;math.ppas,1593 :: 		
$05B1	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$05B2	$	_LOOP:
;math.ppas,1603 :: 		
$05B2	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$05B3	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$05B4	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$05B5	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$05B6	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$05B7	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$05B8	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$05B9	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$05BA	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$05BB	$2DAE			GOTO	_NEXT
;math.ppas,1617 :: 		
$05BC	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$05BD	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$05BE	$2DCE			GOTO	_EXIT1
;math.ppas,1626 :: 		
$05BF	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$05C0	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$05C1	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$05C2	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$05C3	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$05C4	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$05C5	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$05C6	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$05C7	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$05C8	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$05C9	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$05CA	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$05CB	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$05CC	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$05CD	$2DB2			GOTO	_LOOP
;math.ppas,1647 :: 		
$05CE	$	_EXIT1:
;math.ppas,1648 :: 		
$05CE	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$05CF	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$05D0	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$05D1	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$05D2	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$05D3	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$05D4	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$05D5	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$05D6	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$05D7	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$05D8	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$05D9	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$05DA	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$05DB	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$05DC	$	_EXIT2:
;math.ppas,1665 :: 		
$05DC	$	math_L_13:
;math.ppas,1666 :: 		
$05DC	$0008			RETURN
$0004	$	_sdiv3232l:
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0006	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0007	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0008	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0009	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$000A	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$000B	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$000C	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$000D	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$000E	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$000F	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0010	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0011	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0012	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0013	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0014	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0015	$3007			MOVLW	7
;math.ppas,559 :: 		
$0016	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0017	$	LOOPS3232A:
;math.ppas,561 :: 		
$0017	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0018	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0019	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$001A	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$001B	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$001C	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$001D	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$001E	$282D			GOTO	SADD22LA
;math.ppas,570 :: 		
$001F	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0020	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0021	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0022	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0023	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0024	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0025	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0026	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0027	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0028	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0029	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$002A	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$002B	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$002C	$283A			GOTO	SOK22LA
;math.ppas,585 :: 		
$002D	$	SADD22LA:
;math.ppas,586 :: 		
$002D	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$002E	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$002F	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0030	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0031	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0032	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0033	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0034	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0035	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0036	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0037	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0038	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0039	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$003A	$	SOK22LA:
;math.ppas,602 :: 		
$003A	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$003B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$003C	$2817			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$003D	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$003E	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$003F	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0040	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0041	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0042	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0043	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0044	$2853			GOTO	SADD22L8
;math.ppas,615 :: 		
$0045	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0046	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0047	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0048	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0049	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$004A	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$004B	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$004C	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$004D	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$004E	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$004F	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0050	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0051	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0052	$2860			GOTO	SOK22L8
;math.ppas,630 :: 		
$0053	$	SADD22L8:
;math.ppas,631 :: 		
$0053	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0054	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0055	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0056	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0057	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0058	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0059	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$005A	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$005B	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$005C	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$005D	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$005E	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$005F	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0060	$	SOK22L8:
;math.ppas,647 :: 		
$0060	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0061	$3007			MOVLW	7
;math.ppas,650 :: 		
$0062	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0063	$	LOOPS3232B:
;math.ppas,652 :: 		
$0063	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0064	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0065	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0066	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0067	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0068	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0069	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$006A	$2879			GOTO	SADD22LB
;math.ppas,661 :: 		
$006B	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$006C	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$006D	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$006E	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$006F	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$0070	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0071	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0072	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0073	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0074	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0075	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0076	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0077	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0078	$2886			GOTO	SOK22LB
;math.ppas,676 :: 		
$0079	$	SADD22LB:
;math.ppas,677 :: 		
$0079	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$007A	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$007B	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$007C	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$007D	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$007E	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$007F	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$0080	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$0081	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$0082	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$0083	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$0084	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$0085	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$0086	$	SOK22LB:
;math.ppas,693 :: 		
$0086	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$0087	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$0088	$2863			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$0089	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$008A	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$008B	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$008C	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$008D	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$008E	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$008F	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$0090	$289F			GOTO	SADD22L16
;math.ppas,706 :: 		
$0091	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$0092	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$0093	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0094	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$0095	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$0096	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0097	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0098	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$0099	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$009A	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$009B	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$009C	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$009D	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$009E	$28AC			GOTO	SOK22L16
;math.ppas,721 :: 		
$009F	$	SADD22L16:
;math.ppas,722 :: 		
$009F	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$00A0	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$00A1	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$00A2	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$00A3	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$00A4	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$00A5	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$00A6	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$00A7	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$00A8	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$00A9	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$00AA	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$00AB	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$00AC	$	SOK22L16:
;math.ppas,738 :: 		
$00AC	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$00AD	$3007			MOVLW	7
;math.ppas,741 :: 		
$00AE	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$00AF	$	LOOPS3232C:
;math.ppas,743 :: 		
$00AF	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$00B0	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$00B1	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$00B2	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$00B3	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$00B4	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$00B5	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$00B6	$28C5			GOTO	SADD22LC
;math.ppas,752 :: 		
$00B7	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$00B8	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$00B9	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$00BA	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$00BB	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$00BC	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$00BD	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$00BE	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$00BF	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$00C0	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$00C1	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$00C2	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$00C3	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$00C4	$28D2			GOTO	SOK22LC
;math.ppas,767 :: 		
$00C5	$	SADD22LC:
;math.ppas,768 :: 		
$00C5	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$00C6	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$00C7	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$00C8	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$00C9	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$00CA	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$00CB	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$00CC	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$00CD	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$00CE	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$00CF	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$00D0	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$00D1	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$00D2	$	SOK22LC:
;math.ppas,784 :: 		
$00D2	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$00D3	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$00D4	$28AF			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$00D5	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$00D6	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$00D7	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$00D8	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$00D9	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$00DA	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$00DB	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$00DC	$28EB			GOTO	SADD22L24
;math.ppas,797 :: 		
$00DD	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$00DE	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$00DF	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$00E0	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$00E1	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$00E2	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$00E3	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$00E4	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$00E5	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$00E6	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$00E7	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$00E8	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$00E9	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$00EA	$28F8			GOTO	SOK22L24
;math.ppas,812 :: 		
$00EB	$	SADD22L24:
;math.ppas,813 :: 		
$00EB	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$00EC	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$00ED	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$00EE	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$00EF	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$00F0	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$00F1	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$00F2	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$00F3	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$00F4	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$00F5	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$00F6	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$00F7	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$00F8	$	SOK22L24:
;math.ppas,829 :: 		
$00F8	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$00F9	$3007			MOVLW	7
;math.ppas,832 :: 		
$00FA	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$00FB	$	LOOPS3232D:
;math.ppas,834 :: 		
$00FB	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$00FC	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$00FD	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$00FE	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$00FF	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0100	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0101	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0102	$2911			GOTO	SADD22LD
;math.ppas,843 :: 		
$0103	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0104	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0105	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0106	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0107	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0108	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0109	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$010A	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$010B	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$010C	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$010D	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$010E	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$010F	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0110	$291E			GOTO	SOK22LD
;math.ppas,858 :: 		
$0111	$	SADD22LD:
;math.ppas,859 :: 		
$0111	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0112	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0113	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0114	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0115	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0116	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0117	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0118	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0119	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$011A	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$011B	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$011C	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$011D	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$011E	$	SOK22LD:
;math.ppas,876 :: 		
$011E	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$011F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0120	$28FB			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0121	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0122	$2931			GOTO	SOK22L
;math.ppas,882 :: 		
$0123	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0124	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0125	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0126	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0127	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0128	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0129	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$012A	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$012B	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$012C	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$012D	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$012E	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$012F	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0130	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0131	$	SOK22L:
;math.ppas,897 :: 		
$0131	$	math_L_9:
;math.ppas,898 :: 		
$0131	$0008			RETURN
$0677	$	_comfrem:
$0677	$1303			BCF	STATUS, RP1
$0678	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$0679	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$067A	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$067B	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$067C	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$067D	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$067E	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$067F	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0680	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0681	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0682	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0683	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0684	$	math_L_10:
;math.ppas,915 :: 		
$0684	$0008			RETURN
$0665	$	_usart_write:
;USART_b75.ppas,40 :: 		
;USART_b75.ppas,42 :: 		
$0665	$	USART_b75_L_14:
$0665	$1303			BCF	STATUS, RP1
$0666	$1683			BSF	STATUS, RP0
$0667	$0818			MOVF	TXSTA, 0
$0668	$00F1			MOVWF	STACK_1
$0669	$3000			MOVLW	0
$066A	$18F1			BTFSC	STACK_1, 1
$066B	$3001			MOVLW	1
$066C	$00F1			MOVWF	STACK_1
$066D	$0871			MOVF	STACK_1, 0
$066E	$3A00			XORLW	0
$066F	$1D03			BTFSS	STATUS, Z
$0670	$2E73			GOTO	USART_b75_L_15
;USART_b75.ppas,43 :: 		
$0671	$0000			NOP
$0672	$2E65			GOTO	USART_b75_L_14
$0673	$	USART_b75_L_15:
;USART_b75.ppas,44 :: 		
$0673	$1283			BCF	STATUS, RP0
$0674	$0854			MOVF	FARG_USART_Write, 0
$0675	$0099			MOVWF	TXREG
$0676	$	USART_b75_L_12:
;USART_b75.ppas,45 :: 		
$0676	$0008			RETURN
$0685	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$0685	$1303			BCF	STATUS, RP1
$0686	$1283			BCF	STATUS, RP0
$0687	$080C			MOVF	PIR1, 0
$0688	$00F1			MOVWF	STACK_1
$0689	$3000			MOVLW	0
$068A	$1AF1			BTFSC	STACK_1, 5
$068B	$3001			MOVLW	1
$068C	$00F1			MOVWF	STACK_1
$068D	$0871			MOVF	STACK_1, 0
$068E	$00CE			MOVWF	_usart_data_ready_local_result
$068F	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$068F	$084E			MOVF	_usart_data_ready_local_result, 0
$0690	$00F0			MOVWF	STACK_0
$0691	$0008			RETURN
$0652	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$0652	$1303			BCF	STATUS, RP1
$0653	$1283			BCF	STATUS, RP0
$0654	$081A			MOVF	RCREG, 0
$0655	$00CE			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$0656	$0818			MOVF	RCSTA, 0
$0657	$00F1			MOVWF	STACK_1
$0658	$3000			MOVLW	0
$0659	$18F1			BTFSC	STACK_1, 1
$065A	$3001			MOVLW	1
$065B	$00F1			MOVWF	STACK_1
$065C	$0871			MOVF	STACK_1, 0
$065D	$3A01			XORLW	1
$065E	$1D03			BTFSS	STATUS, Z
$065F	$2E62			GOTO	USART_b75_L_21
$0660	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$0660	$1218			BCF	RCSTA, 4
$0661	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$0661	$	USART_b75_L_25:
$0661	$1618			BSF	RCSTA, 4
$0662	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$0662	$	USART_b75_L_21:
$0662	$	USART_b75_L_22:
$0662	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$0662	$084E			MOVF	_usart_read_local_result, 0
$0663	$00F0			MOVWF	STACK_0
$0664	$0008			RETURN
$056B	$	_mul_32x32_s:
$056B	$1303			BCF	STATUS, RP1
$056C	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$056D	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$056E	$	_IF_FIRST:
;math.ppas,1684 :: 		
$056E	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$056F	$2D7D			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$0570	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$0570	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$0571	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$0572	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$0573	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$0574	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$0575	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$0576	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$0577	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$0578	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$0579	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$057A	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$057B	$3081			MOVLW	129
;math.ppas,1711 :: 		
$057C	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$057D	$	_IF_SECOND:
;math.ppas,1715 :: 		
$057D	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$057E	$2D8B			GOTO	_MULT
;math.ppas,1722 :: 		
$057F	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$057F	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$0580	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$0581	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$0582	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$0583	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$0584	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$0585	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$0586	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$0587	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$0588	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$0589	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$058A	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$058B	$	_MULT:
;math.ppas,1744 :: 		
$058B	$25A6			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$058C	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$058D	$2DA5			GOTO	_EXIT
;math.ppas,1755 :: 		
$058E	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$058F	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$0590	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$0591	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$0592	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$0593	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$0594	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$0595	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$0596	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$0597	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$0598	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$0599	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$059A	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$059B	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$059C	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$059D	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$059E	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$059F	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$05A0	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$05A1	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$05A2	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$05A3	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$05A4	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$05A5	$	_EXIT:
;math.ppas,1793 :: 		
$05A5	$	math_L_14:
;math.ppas,1794 :: 		
$05A5	$0008			RETURN
$060A	$	_div_16x16_u:
$060A	$1303			BCF	STATUS, RP1
$060B	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$060C	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$060D	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$060E	$3010			MOVLW	16
;math.ppas,113 :: 		
$060F	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0610	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0611	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0612	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0613	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$0614	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0615	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0616	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0617	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0618	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0619	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$061A	$2E22			GOTO	$+8
;math.ppas,125 :: 		
$061B	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$061C	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$061D	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$061E	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$061F	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0620	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0621	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0622	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$0623	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$0624	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0625	$2E10			GOTO	$-21
;math.ppas,136 :: 		
$0626	$	math_L_3:
;math.ppas,137 :: 		
$0626	$0008			RETURN
$02A2	$	_div_32x32_s:
$02A2	$1303			BCF	STATUS, RP1
$02A3	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$02A4	$	FXD3232S:
;math.ppas,929 :: 		
$02A4	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$02A5	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$02A6	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$02A7	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$02A8	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$02A9	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$02AA	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$02AB	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$02AC	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$02AD	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$02AE	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$02AF	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$02B0	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$02B1	$2B36			GOTO	END_ALL
;math.ppas,944 :: 		
$02B2	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$02B3	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$02B4	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$02B5	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$02B6	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$02B7	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$02B8	$2AC4			GOTO	CA3232S
;math.ppas,955 :: 		
$02B9	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$02BA	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$02BB	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$02BC	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$02BD	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$02BE	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$02BF	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$02C0	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$02C1	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$02C2	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$02C3	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$02C4	$	CA3232S:
;math.ppas,968 :: 		
$02C4	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$02C5	$2AD1			GOTO	C3232SX
;math.ppas,971 :: 		
$02C6	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$02C7	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$02C8	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$02C9	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$02CA	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$02CB	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$02CC	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$02CD	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$02CE	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$02CF	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$02D0	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$02D1	$	C3232SX:
;math.ppas,984 :: 		
$02D1	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$02D2	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$02D3	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$02D4	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$02D5	$2AF2			GOTO	C3232SX1
;math.ppas,989 :: 		
$02D6	$	C3232S:
;math.ppas,992 :: 		
$02D6	$2004			CALL	_sdiv3232l
;math.ppas,995 :: 		
$02D7	$	C3232S2:
;math.ppas,996 :: 		
$02D7	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$02D8	$2B0F			GOTO	C3232SX4
;math.ppas,998 :: 		
$02D9	$	C3232SOK:
;math.ppas,999 :: 		
$02D9	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$02DA	$2B36			GOTO	END_ALL
;math.ppas,1001 :: 		
$02DB	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$02DC	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$02DD	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$02DE	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$02DF	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$02E0	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$02E1	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$02E2	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$02E3	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$02E4	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$02E5	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$02E6	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$02E7	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$02E8	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$02E9	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$02EA	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$02EB	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$02EC	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$02ED	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$02EE	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$02EF	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$02F0	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$02F1	$2B36			GOTO	END_ALL
;math.ppas,1026 :: 		
$02F2	$	C3232SX1:
;math.ppas,1027 :: 		
$02F2	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$02F3	$2B09			GOTO	C3232SX3
;math.ppas,1029 :: 		
$02F4	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$02F5	$2B03			GOTO	C3232SX2
;math.ppas,1031 :: 		
$02F6	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$02F7	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$02F8	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$02F9	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$02FA	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$02FB	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$02FC	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$02FD	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$02FE	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$02FF	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0300	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0301	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0302	$2AD9			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0303	$	C3232SX2:
;math.ppas,1045 :: 		
$0303	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0304	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0305	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0306	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0307	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$0308	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$0309	$	C3232SX3:
;math.ppas,1053 :: 		
$0309	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$030A	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$030B	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$030C	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$030D	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$030E	$2AD6			GOTO	C3232S
;math.ppas,1061 :: 		
$030F	$	C3232SX4:
;math.ppas,1062 :: 		
$030F	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0310	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0311	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0312	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0313	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0314	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0315	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0316	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0317	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$0318	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$0319	$2AD9			GOTO	C3232SOK
;math.ppas,1073 :: 		
$031A	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$031B	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$031C	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$031D	$2AD9			GOTO	C3232SOK
;math.ppas,1077 :: 		
$031E	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$031F	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0320	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0321	$2AD9			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0322	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0323	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0324	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$0325	$2AD9			GOTO	C3232SOK
;math.ppas,1085 :: 		
$0326	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$0327	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$0328	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$0329	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$032A	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$032B	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$032C	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$032D	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$032E	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$032F	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0330	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0331	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0332	$2AD9			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0333	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0334	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0335	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0336	$	END_ALL:
;math.ppas,1102 :: 		
$0336	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$0337	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$0338	$2B3A			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$0339	$2677			CALL	_comfrem
;math.ppas,1108 :: 		
$033A	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$033A	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$033B	$	math_L_11:
;math.ppas,1111 :: 		
$033B	$0008			RETURN
$033C	$	_vdelay_ms:
;delays.pbas,65 :: 		dim NumberOfCyc as dword
;delays.pbas,67 :: 		NumberOfCyc = Clock_kHz >> 2 ' this will be done by compiler, no asm will be genereated except that for assignment
$033C	$30E8			MOVLW	232
$033D	$1303			BCF	STATUS, RP1
$033E	$1283			BCF	STATUS, RP0
$033F	$00D0			MOVWF	_vdelay_ms_local_numberofcyc
$0340	$3003			MOVLW	3
$0341	$00D1			MOVWF	_vdelay_ms_local_numberofcyc+1
$0342	$01D2			CLRF	_vdelay_ms_local_numberofcyc+2
$0343	$01D3			CLRF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,68 :: 		NumberOfCyc = Time_ms * NumberOfCyc
$0344	$084E			MOVF	FARG_VDelay_ms, 0
$0345	$00F0			MOVWF	STACK_0
$0346	$084F			MOVF	FARG_VDelay_ms+1, 0
$0347	$00F1			MOVWF	STACK_0+1
$0348	$01F2			CLRF	STACK_0+2
$0349	$01F3			CLRF	STACK_0+3
$034A	$30E8			MOVLW	232
$034B	$00F4			MOVWF	STACK_4
$034C	$3003			MOVLW	3
$034D	$00F5			MOVWF	STACK_4+1
$034E	$3000			MOVLW	0
$034F	$00F6			MOVWF	STACK_4+2
$0350	$3000			MOVLW	0
$0351	$00F7			MOVWF	STACK_4+3
$0352	$25A6			CALL	_mul_32x32_u
$0353	$0870			MOVF	STACK_0, 0
$0354	$00D0			MOVWF	_vdelay_ms_local_numberofcyc
$0355	$0871			MOVF	STACK_0+1, 0
$0356	$00D1			MOVWF	_vdelay_ms_local_numberofcyc+1
$0357	$0872			MOVF	STACK_0+2, 0
$0358	$00D2			MOVWF	_vdelay_ms_local_numberofcyc+2
$0359	$0873			MOVF	STACK_0+3, 0
$035A	$00D3			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,69 :: 		if NumberOfCyc < 675 then
$035B	$3000			MOVLW	0
$035C	$0273			SUBWF	STACK_0+3, 0
$035D	$1D03			BTFSS	STATUS, Z
$035E	$2B69			GOTO	L_VDelay_ms_0
$035F	$3000			MOVLW	0
$0360	$0272			SUBWF	STACK_0+2, 0
$0361	$1D03			BTFSS	STATUS, Z
$0362	$2B69			GOTO	L_VDelay_ms_0
$0363	$3002			MOVLW	2
$0364	$0271			SUBWF	STACK_0+1, 0
$0365	$1D03			BTFSS	STATUS, Z
$0366	$2B69			GOTO	L_VDelay_ms_0
$0367	$30A3			MOVLW	163
$0368	$0270			SUBWF	STACK_0, 0
$0369	$	L_VDelay_ms_0:
$0369	$1803			BTFSC	STATUS, C
$036A	$2B6C			GOTO	delays_L_19
$036B	$	delays_L_18:
;delays.pbas,70 :: 		exit
$036B	$2BC3			GOTO	delays_L_17
$036C	$	delays_L_19:
;delays.pbas,71 :: 		end if
$036C	$	delays_L_20:
;delays.pbas,72 :: 		NumberOfCyc = NumberOfCyc - 675
$036C	$30A3			MOVLW	163
$036D	$00F0			MOVWF	STACK_0
$036E	$3002			MOVLW	2
$036F	$00F1			MOVWF	STACK_0+1
$0370	$01F2			CLRF	STACK_0+2
$0371	$01F3			CLRF	STACK_0+3
$0372	$0850			MOVF	_vdelay_ms_local_numberofcyc, 0
$0373	$00F4			MOVWF	STACK_4
$0374	$0851			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$0375	$00F5			MOVWF	STACK_4+1
$0376	$0852			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$0377	$00F6			MOVWF	STACK_4+2
$0378	$0853			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$0379	$00F7			MOVWF	STACK_4+3
$037A	$0870			MOVF	STACK_0, 0
$037B	$02F4			SUBWF	STACK_4, 1
$037C	$0871			MOVF	STACK_0+1, 0
$037D	$1C03			BTFSS	STATUS, C
$037E	$0F71			INCFSZ	STACK_0+1, 0
$037F	$02F5			SUBWF	STACK_4+1, 1
$0380	$0872			MOVF	STACK_0+2, 0
$0381	$1C03			BTFSS	STATUS, C
$0382	$0F72			INCFSZ	STACK_0+2, 0
$0383	$02F6			SUBWF	STACK_4+2, 1
$0384	$0873			MOVF	STACK_0+3, 0
$0385	$1C03			BTFSS	STATUS, C
$0386	$0F73			INCFSZ	STACK_0+3, 0
$0387	$02F7			SUBWF	STACK_4+3, 1
$0388	$0874			MOVF	STACK_4, 0
$0389	$00D0			MOVWF	_vdelay_ms_local_numberofcyc
$038A	$0875			MOVF	STACK_4+1, 0
$038B	$00D1			MOVWF	_vdelay_ms_local_numberofcyc+1
$038C	$0876			MOVF	STACK_4+2, 0
$038D	$00D2			MOVWF	_vdelay_ms_local_numberofcyc+2
$038E	$0877			MOVF	STACK_4+3, 0
$038F	$00D3			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,73 :: 		NumberOfCyc = NumberOfCyc >> 5  ' Dec and While below take around 32 instructions
$0390	$3005			MOVLW	5
$0391	$00F0			MOVWF	STACK_0
$0392	$0874			MOVF	STACK_4, 0
$0393	$00D0			MOVWF	_vdelay_ms_local_numberofcyc
$0394	$0875			MOVF	STACK_4+1, 0
$0395	$00D1			MOVWF	_vdelay_ms_local_numberofcyc+1
$0396	$0876			MOVF	STACK_4+2, 0
$0397	$00D2			MOVWF	_vdelay_ms_local_numberofcyc+2
$0398	$0877			MOVF	STACK_4+3, 0
$0399	$00D3			MOVWF	_vdelay_ms_local_numberofcyc+3
$039A	$0870			MOVF	STACK_0, 0
$039B	$	L_VDelay_ms_1:
$039B	$1903			BTFSC	STATUS, Z
$039C	$2BA4			GOTO	L_VDelay_ms_2
$039D	$0CD3			RRF	_vdelay_ms_local_numberofcyc+3, 1
$039E	$0CD2			RRF	_vdelay_ms_local_numberofcyc+2, 1
$039F	$0CD1			RRF	_vdelay_ms_local_numberofcyc+1, 1
$03A0	$0CD0			RRF	_vdelay_ms_local_numberofcyc, 1
$03A1	$13D3			BCF	_vdelay_ms_local_numberofcyc+3, 7
$03A2	$3FFF			ADDLW	255
$03A3	$2B9B			GOTO	L_VDelay_ms_1
$03A4	$	L_VDelay_ms_2:
;delays.pbas,74 :: 		while ( Lo(NumberOfCyc) or Hi(NumberOfCyc) or Higher(NumberOfCyc) or Highest(NumberOfCyc) ) <> 0
$03A4	$	delays_L_22:
$03A4	$30FF			MOVLW	255
$03A5	$0550			ANDWF	_vdelay_ms_local_numberofcyc, 0
$03A6	$00F8			MOVWF	STACK_8
$03A7	$0851			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$03A8	$00F0			MOVWF	STACK_0
$03A9	$0870			MOVF	STACK_0, 0
$03AA	$04F8			IORWF	STACK_8, 1
$03AB	$0852			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$03AC	$00F0			MOVWF	STACK_0
$03AD	$0853			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$03AE	$00F1			MOVWF	STACK_0+1
$03AF	$0870			MOVF	STACK_0, 0
$03B0	$04F8			IORWF	STACK_8, 1
$03B1	$0853			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$03B2	$00F0			MOVWF	STACK_0
$03B3	$0870			MOVF	STACK_0, 0
$03B4	$0478			IORWF	STACK_8, 0
$03B5	$00F4			MOVWF	STACK_4
$03B6	$0874			MOVF	STACK_4, 0
$03B7	$3A00			XORLW	0
$03B8	$1903			BTFSC	STATUS, Z
$03B9	$2BC3			GOTO	delays_L_23
;delays.pbas,75 :: 		Dec(NumberOfCyc)
$03BA	$3001			MOVLW	1
$03BB	$02D0			SUBWF	_vdelay_ms_local_numberofcyc, 1
$03BC	$1C03			BTFSS	STATUS, C
$03BD	$02D1			SUBWF	_vdelay_ms_local_numberofcyc+1, 1
$03BE	$1C03			BTFSS	STATUS, C
$03BF	$02D2			SUBWF	_vdelay_ms_local_numberofcyc+2, 1
$03C0	$1C03			BTFSS	STATUS, C
$03C1	$02D3			SUBWF	_vdelay_ms_local_numberofcyc+3, 1
$03C2	$2BA4			GOTO	delays_L_22
$03C3	$	delays_L_23:
;delays.pbas,76 :: 		wend
$03C3	$	delays_L_17:
$03C3	$0008			RETURN
$0627	$	_usart_write_text:
;USART_b75.ppas,121 :: 		
;USART_b75.ppas,122 :: 		
$0627	$1303			BCF	STATUS, RP1
$0628	$1283			BCF	STATUS, RP0
$0629	$01CF			CLRF	_usart_write_text_local_i, 1
;USART_b75.ppas,123 :: 		
$062A	$084E			MOVF	FARG_Usart_Write_Text, 0
$062B	$0084			MOVWF	FSR
$062C	$0800			MOVF	INDF, 0
$062D	$00D0			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,124 :: 		
$062E	$	USART_b75_L_47:
$062E	$0850			MOVF	_usart_write_text_local_data, 0
$062F	$3A00			XORLW	0
$0630	$1903			BTFSC	STATUS, Z
$0631	$2E3C			GOTO	USART_b75_L_48
;USART_b75.ppas,126 :: 		
$0632	$0850			MOVF	_usart_write_text_local_data, 0
$0633	$00D4			MOVWF	FARG_USART_Write
$0634	$2665			CALL	_usart_write
;USART_b75.ppas,127 :: 		
$0635	$0ACF			INCF	_usart_write_text_local_i, 1
;USART_b75.ppas,128 :: 		
$0636	$084F			MOVF	_usart_write_text_local_i, 0
$0637	$074E			ADDWF	FARG_Usart_Write_Text, 0
$0638	$0084			MOVWF	FSR
$0639	$0800			MOVF	INDF, 0
$063A	$00D0			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,129 :: 		
$063B	$2E2E			GOTO	USART_b75_L_47
$063C	$	USART_b75_L_48:
$063C	$	USART_b75_L_45:
;USART_b75.ppas,130 :: 		
$063C	$0008			RETURN
$05DD	$	_div_16x16_s_l:
$05DD	$1303			BCF	STATUS, RP1
$05DE	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$05DF	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$05E0	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$05E1	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$05E2	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$05E3	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$05E4	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$05E5	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$05E6	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$05E7	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$05E8	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$05E9	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$05EA	$300F			MOVLW	15
;math.ppas,307 :: 		
$05EB	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$05EC	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$05ED	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$05EE	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$05EF	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$05F0	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$05F1	$2DF8			GOTO	$+7
;math.ppas,315 :: 		
$05F2	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$05F3	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$05F4	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$05F5	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$05F6	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$05F7	$2DFD			GOTO	$+6
;math.ppas,322 :: 		
$05F8	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$05F9	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$05FA	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$05FB	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$05FC	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$05FD	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$05FE	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$05FF	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$0600	$2DEC			GOTO	$-20
;math.ppas,334 :: 		
$0601	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$0602	$2E09			GOTO	$+7
;math.ppas,336 :: 		
$0603	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$0604	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$0605	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$0606	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$0607	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$0608	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$0609	$	math_L_6:
;math.ppas,343 :: 		
$0609	$0008			RETURN
$0499	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$0499	$1303			BCF	STATUS, RP1
$049A	$1283			BCF	STATUS, RP0
$049B	$01C3			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$049C	$01C4			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$049D	$01C7			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$049E	$0842			MOVF	FARG_Usart_Read_Text+1, 0
$049F	$0084			MOVWF	FSR
$04A0	$0800			MOVF	INDF, 0
$04A1	$00C6			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$04A2	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$04A2	$2685			CALL	_usart_data_ready
$04A3	$0870			MOVF	STACK_0, 0
$04A4	$3A00			XORLW	0
$04A5	$1903			BTFSC	STATUS, Z
$04A6	$2CD2			GOTO	USART_b75_L_34
$04A7	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$04A7	$2652			CALL	_usart_read
$04A8	$0870			MOVF	STACK_0, 0
$04A9	$00C5			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$04AA	$0843			MOVF	_usart_read_text_local_i, 0
$04AB	$0741			ADDWF	FARG_Usart_Read_Text, 0
$04AC	$00F1			MOVWF	STACK_1
$04AD	$0871			MOVF	STACK_1, 0
$04AE	$0084			MOVWF	FSR
$04AF	$0871			MOVF	STACK_1, 0
$04B0	$0084			MOVWF	FSR
$04B1	$0870			MOVF	STACK_0, 0
$04B2	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$04B3	$0845			MOVF	_usart_read_text_local_data, 0
$04B4	$0646			XORWF	_usart_read_text_local_data2, 0
$04B5	$1D03			BTFSS	STATUS, Z
$04B6	$2CBC			GOTO	USART_b75_L_37
$04B7	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$04B7	$0844			MOVF	_usart_read_text_local_j, 0
$04B8	$0243			SUBWF	_usart_read_text_local_i, 0
$04B9	$00C7			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$04BA	$0AC4			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$04BB	$2CBE			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$04BC	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$04BC	$01C4			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$04BD	$01C7			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$04BE	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$04BE	$0844			MOVF	_usart_read_text_local_j, 0
$04BF	$0742			ADDWF	FARG_Usart_Read_Text+1, 0
$04C0	$0084			MOVWF	FSR
$04C1	$0800			MOVF	INDF, 0
$04C2	$00F1			MOVWF	STACK_1
$04C3	$0871			MOVF	STACK_1, 0
$04C4	$00C6			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$04C5	$0871			MOVF	STACK_1, 0
$04C6	$3A00			XORLW	0
$04C7	$1D03			BTFSS	STATUS, Z
$04C8	$2CCA			GOTO	USART_b75_L_40
$04C9	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$04C9	$2CD3			GOTO	USART_b75_L_30
$04CA	$	USART_b75_L_40:
$04CA	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$04CA	$0AC3			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$04CB	$0843			MOVF	_usart_read_text_local_i, 0
$04CC	$3C14			SUBLW	20
$04CD	$1803			BTFSC	STATUS, C
$04CE	$2CD2			GOTO	USART_b75_L_43
$04CF	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$04CF	$3013			MOVLW	19
$04D0	$00C7			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$04D1	$2CD3			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$04D2	$	USART_b75_L_43:
$04D2	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$04D2	$	USART_b75_L_34:
$04D2	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$04D2	$2CA2			GOTO	USART_b75_L_29
$04D3	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$04D3	$0847			MOVF	_usart_read_text_local_lasti, 0
$04D4	$0741			ADDWF	FARG_Usart_Read_Text, 0
$04D5	$00F0			MOVWF	STACK_0
$04D6	$0870			MOVF	STACK_0, 0
$04D7	$0084			MOVWF	FSR
$04D8	$0870			MOVF	STACK_0, 0
$04D9	$0084			MOVWF	FSR
$04DA	$0180			CLRF	INDF, 1
$04DB	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$04DB	$0008			RETURN
$01E0	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$01E0	$1303			BCF	STATUS, RP1
$01E1	$1283			BCF	STATUS, RP0
$01E2	$01C2			CLRF	_strtoint_local_result
$01E3	$01C3			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$01E4	$3010			MOVLW	16
$01E5	$00C6			MOVWF	_strtoint_local_ep
$01E6	$3027			MOVLW	39
$01E7	$00C7			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$01E8	$01C4			CLRF	_strtoint_local_i
$01E9	$01C5			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$01EA	$01CA			CLRF	_strtoint_local_tmp
$01EB	$01CB			CLRF	_strtoint_local_tmp+1
$01EC	$01CC			CLRF	_strtoint_local_tmp+2
$01ED	$01CD			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$01EE	$01C8			CLRF	_strtoint_local_negative
$01EF	$01C9			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$01F0	$	conv_L_172:
$01F0	$0844			MOVF	_strtoint_local_i, 0
$01F1	$0741			ADDWF	FARG_StrToInt, 0
$01F2	$0084			MOVWF	FSR
$01F3	$0800			MOVF	INDF, 0
$01F4	$00F4			MOVWF	STACK_4
$01F5	$0874			MOVF	STACK_4, 0
$01F6	$3A00			XORLW	0
$01F7	$1903			BTFSC	STATUS, Z
$01F8	$2A5C			GOTO	conv_L_173
;conv.ppas,355 :: 		
$01F9	$0844			MOVF	_strtoint_local_i, 0
$01FA	$0741			ADDWF	FARG_StrToInt, 0
$01FB	$0084			MOVWF	FSR
$01FC	$0800			MOVF	INDF, 0
$01FD	$00F4			MOVWF	STACK_4
$01FE	$0874			MOVF	STACK_4, 0
$01FF	$3A2D			XORLW	45
$0200	$1D03			BTFSS	STATUS, Z
$0201	$2A09			GOTO	conv_L_177
$0202	$	conv_L_176:
;conv.ppas,357 :: 		
$0202	$30FF			MOVLW	255
$0203	$00C8			MOVWF	_strtoint_local_negative
$0204	$01C9			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$0205	$0AC4			INCF	_strtoint_local_i, 1
$0206	$1903			BTFSC	STATUS, Z
$0207	$0AC5			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$0208	$29F0			GOTO	conv_L_172
;conv.ppas,360 :: 		
$0209	$	conv_L_177:
$0209	$	conv_L_178:
;conv.ppas,361 :: 		
$0209	$0844			MOVF	_strtoint_local_i, 0
$020A	$0741			ADDWF	FARG_StrToInt, 0
$020B	$0084			MOVWF	FSR
$020C	$0800			MOVF	INDF, 0
$020D	$00F4			MOVWF	STACK_4
$020E	$0874			MOVF	STACK_4, 0
$020F	$3A20			XORLW	32
$0210	$1903			BTFSC	STATUS, Z
$0211	$2A4C			GOTO	conv_L_180
$0212	$	conv_L_179:
;conv.ppas,362 :: 		
$0212	$0844			MOVF	_strtoint_local_i, 0
$0213	$0741			ADDWF	FARG_StrToInt, 0
$0214	$0084			MOVWF	FSR
$0215	$0800			MOVF	INDF, 0
$0216	$00F0			MOVWF	STACK_0
$0217	$3030			MOVLW	48
$0218	$00F8			MOVWF	STACK_8
$0219	$01F9			CLRF	STACK_8+1
$021A	$01FA			CLRF	STACK_8+2
$021B	$01FB			CLRF	STACK_8+3
$021C	$0870			MOVF	STACK_0, 0
$021D	$00F4			MOVWF	STACK_4
$021E	$01F5			CLRF	STACK_4+1
$021F	$01F6			CLRF	STACK_4+2
$0220	$01F7			CLRF	STACK_4+3
$0221	$0874			MOVF	STACK_4, 0
$0222	$00F0			MOVWF	STACK_0
$0223	$0875			MOVF	STACK_4+1, 0
$0224	$00F1			MOVWF	STACK_0+1
$0225	$0876			MOVF	STACK_4+2, 0
$0226	$00F2			MOVWF	STACK_0+2
$0227	$0877			MOVF	STACK_4+3, 0
$0228	$00F3			MOVWF	STACK_0+3
$0229	$0878			MOVF	STACK_8, 0
$022A	$02F0			SUBWF	STACK_0, 1
$022B	$0879			MOVF	STACK_8+1, 0
$022C	$1C03			BTFSS	STATUS, C
$022D	$0F79			INCFSZ	STACK_8+1, 0
$022E	$02F1			SUBWF	STACK_0+1, 1
$022F	$087A			MOVF	STACK_8+2, 0
$0230	$1C03			BTFSS	STATUS, C
$0231	$0F7A			INCFSZ	STACK_8+2, 0
$0232	$02F2			SUBWF	STACK_0+2, 1
$0233	$087B			MOVF	STACK_8+3, 0
$0234	$1C03			BTFSS	STATUS, C
$0235	$0F7B			INCFSZ	STACK_8+3, 0
$0236	$02F3			SUBWF	STACK_0+3, 1
$0237	$0846			MOVF	_strtoint_local_ep, 0
$0238	$00F4			MOVWF	STACK_4
$0239	$0847			MOVF	_strtoint_local_ep+1, 0
$023A	$00F5			MOVWF	STACK_4+1
$023B	$01F6			CLRF	STACK_4+2
$023C	$01F7			CLRF	STACK_4+3
$023D	$256B			CALL	_mul_32x32_s
$023E	$0870			MOVF	STACK_0, 0
$023F	$07CA			ADDWF	_strtoint_local_tmp, 1
$0240	$0871			MOVF	STACK_0+1, 0
$0241	$1803			BTFSC	STATUS, C
$0242	$0F71			INCFSZ	STACK_0+1, 0
$0243	$07CB			ADDWF	_strtoint_local_tmp+1, 1
$0244	$0872			MOVF	STACK_0+2, 0
$0245	$1803			BTFSC	STATUS, C
$0246	$0F72			INCFSZ	STACK_0+2, 0
$0247	$07CC			ADDWF	_strtoint_local_tmp+2, 1
$0248	$0873			MOVF	STACK_0+3, 0
$0249	$1803			BTFSC	STATUS, C
$024A	$0F73			INCFSZ	STACK_0+3, 0
$024B	$07CD			ADDWF	_strtoint_local_tmp+3, 1
$024C	$	conv_L_180:
$024C	$	conv_L_181:
;conv.ppas,363 :: 		
$024C	$300A			MOVLW	10
$024D	$00F4			MOVWF	STACK_4
$024E	$01F5			CLRF	STACK_4+1
$024F	$0846			MOVF	_strtoint_local_ep, 0
$0250	$00F0			MOVWF	STACK_0
$0251	$0847			MOVF	_strtoint_local_ep+1, 0
$0252	$00F1			MOVWF	STACK_0+1
$0253	$260A			CALL	_div_16x16_u
$0254	$0870			MOVF	STACK_0, 0
$0255	$00C6			MOVWF	_strtoint_local_ep
$0256	$0871			MOVF	STACK_0+1, 0
$0257	$00C7			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$0258	$0AC4			INCF	_strtoint_local_i, 1
$0259	$1903			BTFSC	STATUS, Z
$025A	$0AC5			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$025B	$29F0			GOTO	conv_L_172
$025C	$	conv_L_173:
;conv.ppas,370 :: 		
$025C	$0848			MOVF	_strtoint_local_negative, 0
$025D	$0449			IORWF	_strtoint_local_negative+1, 0
$025E	$1903			BTFSC	STATUS, Z
$025F	$2A64			GOTO	conv_L_183
$0260	$	conv_L_182:
$0260	$3006			MOVLW	6
$0261	$00C6			MOVWF	_strtoint_local_ep
$0262	$01C7			CLRF	_strtoint_local_ep+1
$0263	$2A67			GOTO	conv_L_184
;conv.ppas,371 :: 		
$0264	$	conv_L_183:
$0264	$3005			MOVLW	5
$0265	$00C6			MOVWF	_strtoint_local_ep
$0266	$01C7			CLRF	_strtoint_local_ep+1
$0267	$	conv_L_184:
;conv.ppas,373 :: 		
$0267	$	conv_L_186:
$0267	$0845			MOVF	_strtoint_local_i+1, 0
$0268	$0647			XORWF	_strtoint_local_ep+1, 0
$0269	$1D03			BTFSS	STATUS, Z
$026A	$2A6D			GOTO	L_StrToInt_20
$026B	$0846			MOVF	_strtoint_local_ep, 0
$026C	$0644			XORWF	_strtoint_local_i, 0
$026D	$	L_StrToInt_20:
$026D	$1903			BTFSC	STATUS, Z
$026E	$2A89			GOTO	conv_L_187
;conv.ppas,375 :: 		
$026F	$300A			MOVLW	10
$0270	$00F4			MOVWF	STACK_4
$0271	$01F5			CLRF	STACK_4+1
$0272	$01F6			CLRF	STACK_4+2
$0273	$01F7			CLRF	STACK_4+3
$0274	$084A			MOVF	_strtoint_local_tmp, 0
$0275	$00F0			MOVWF	STACK_0
$0276	$084B			MOVF	_strtoint_local_tmp+1, 0
$0277	$00F1			MOVWF	STACK_0+1
$0278	$084C			MOVF	_strtoint_local_tmp+2, 0
$0279	$00F2			MOVWF	STACK_0+2
$027A	$084D			MOVF	_strtoint_local_tmp+3, 0
$027B	$00F3			MOVWF	STACK_0+3
$027C	$22A2			CALL	_div_32x32_s
$027D	$0870			MOVF	STACK_0, 0
$027E	$00CA			MOVWF	_strtoint_local_tmp
$027F	$0871			MOVF	STACK_0+1, 0
$0280	$00CB			MOVWF	_strtoint_local_tmp+1
$0281	$0872			MOVF	STACK_0+2, 0
$0282	$00CC			MOVWF	_strtoint_local_tmp+2
$0283	$0873			MOVF	STACK_0+3, 0
$0284	$00CD			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$0285	$0AC4			INCF	_strtoint_local_i, 1
$0286	$1903			BTFSC	STATUS, Z
$0287	$0AC5			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$0288	$2A67			GOTO	conv_L_186
$0289	$	conv_L_187:
;conv.ppas,380 :: 		
$0289	$084A			MOVF	_strtoint_local_tmp, 0
$028A	$00C2			MOVWF	_strtoint_local_result
$028B	$084B			MOVF	_strtoint_local_tmp+1, 0
$028C	$00C3			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$028D	$3000			MOVLW	0
$028E	$0649			XORWF	_strtoint_local_negative+1, 0
$028F	$1D03			BTFSS	STATUS, Z
$0290	$2A93			GOTO	L_StrToInt_21
$0291	$30FF			MOVLW	255
$0292	$0648			XORWF	_strtoint_local_negative, 0
$0293	$	L_StrToInt_21:
$0293	$1D03			BTFSS	STATUS, Z
$0294	$2A9D			GOTO	conv_L_191
$0295	$	conv_L_190:
;conv.ppas,383 :: 		
$0295	$0842			MOVF	_strtoint_local_result, 0
$0296	$3C00			SUBLW	0
$0297	$00C2			MOVWF	_strtoint_local_result
$0298	$0843			MOVF	_strtoint_local_result+1, 0
$0299	$1C03			BTFSS	STATUS, C
$029A	$3F01			ADDLW	1
$029B	$01C3			CLRF	_strtoint_local_result+1
$029C	$02C3			SUBWF	_strtoint_local_result+1, 1
$029D	$	conv_L_191:
$029D	$	conv_L_192:
$029D	$	conv_L_170:
;conv.ppas,384 :: 		
$029D	$0842			MOVF	_strtoint_local_result, 0
$029E	$00F0			MOVWF	STACK_0
$029F	$0843			MOVF	_strtoint_local_result+1, 0
$02A0	$00F1			MOVWF	STACK_0+1
$02A1	$0008			RETURN
$0525	$	_strcmp:
;StringsLib.ppas,172 :: 		
;StringsLib.ppas,173 :: 		
$0525	$1303			BCF	STATUS, RP1
$0526	$1283			BCF	STATUS, RP0
$0527	$01C5			CLRF	_strcmp_local_i, 1
;StringsLib.ppas,174 :: 		
$0528	$0841			MOVF	FARG_strcmp, 0
$0529	$0084			MOVWF	FSR
$052A	$0800			MOVF	INDF, 0
$052B	$00C3			MOVWF	_strcmp_local_result
$052C	$01C4			CLRF	_strcmp_local_result+1
;StringsLib.ppas,175 :: 		
$052D	$0842			MOVF	FARG_strcmp+1, 0
$052E	$0084			MOVWF	FSR
$052F	$0800			MOVF	INDF, 0
$0530	$00F0			MOVWF	STACK_0
;StringsLib.ppas,176 :: 		
$0531	$3000			MOVLW	0
$0532	$00C4			MOVWF	_strcmp_local_result+1
$0533	$0870			MOVF	STACK_0, 0
$0534	$02C3			SUBWF	_strcmp_local_result, 1
$0535	$1C03			BTFSS	STATUS, C
$0536	$03C4			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,177 :: 		
$0537	$	StringsLib_L_77:
$0537	$3000			MOVLW	0
$0538	$0644			XORWF	_strcmp_local_result+1, 0
$0539	$1D03			BTFSS	STATUS, Z
$053A	$2D3D			GOTO	L_strcmp_8
$053B	$3000			MOVLW	0
$053C	$0643			XORWF	_strcmp_local_result, 0
$053D	$	L_strcmp_8:
$053D	$30FF			MOVLW	255
$053E	$1D03			BTFSS	STATUS, Z
$053F	$3000			MOVLW	0
$0540	$00F3			MOVWF	STACK_3
$0541	$0845			MOVF	_strcmp_local_i, 0
$0542	$0741			ADDWF	FARG_strcmp, 0
$0543	$0084			MOVWF	FSR
$0544	$0800			MOVF	INDF, 0
$0545	$00F2			MOVWF	STACK_2
$0546	$0872			MOVF	STACK_2, 0
$0547	$3A00			XORLW	0
$0548	$30FF			MOVLW	255
$0549	$1903			BTFSC	STATUS, Z
$054A	$3000			MOVLW	0
$054B	$00F0			MOVWF	STACK_0
$054C	$0873			MOVF	STACK_3, 0
$054D	$05F0			ANDWF	STACK_0, 1
$054E	$1903			BTFSC	STATUS, Z
$054F	$2D66			GOTO	StringsLib_L_78
;StringsLib.ppas,179 :: 		
$0550	$0A45			INCF	_strcmp_local_i, 0
$0551	$00F0			MOVWF	STACK_0
$0552	$0870			MOVF	STACK_0, 0
$0553	$00C5			MOVWF	_strcmp_local_i
;StringsLib.ppas,180 :: 		
$0554	$0870			MOVF	STACK_0, 0
$0555	$0741			ADDWF	FARG_strcmp, 0
$0556	$0084			MOVWF	FSR
$0557	$0800			MOVF	INDF, 0
$0558	$00C3			MOVWF	_strcmp_local_result
$0559	$01C4			CLRF	_strcmp_local_result+1
;StringsLib.ppas,181 :: 		
$055A	$0870			MOVF	STACK_0, 0
$055B	$0742			ADDWF	FARG_strcmp+1, 0
$055C	$0084			MOVWF	FSR
$055D	$0800			MOVF	INDF, 0
$055E	$00F0			MOVWF	STACK_0
;StringsLib.ppas,182 :: 		
$055F	$3000			MOVLW	0
$0560	$00C4			MOVWF	_strcmp_local_result+1
$0561	$0870			MOVF	STACK_0, 0
$0562	$02C3			SUBWF	_strcmp_local_result, 1
$0563	$1C03			BTFSS	STATUS, C
$0564	$03C4			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,183 :: 		
$0565	$2D37			GOTO	StringsLib_L_77
$0566	$	StringsLib_L_78:
$0566	$	StringsLib_L_75:
;StringsLib.ppas,184 :: 		
$0566	$0843			MOVF	_strcmp_local_result, 0
$0567	$00F0			MOVWF	STACK_0
$0568	$0844			MOVF	_strcmp_local_result+1, 0
$0569	$00F1			MOVWF	STACK_0+1
$056A	$0008			RETURN
$03C4	$	_ciclo:
;ControleSerial.pbas,16 :: 		dim x as integer
;ControleSerial.pbas,19 :: 		if passo=true then
$03C4	$1303			BCF	STATUS, RP1
$03C5	$1283			BCF	STATUS, RP0
$03C6	$0821			MOVF	_passo, 0
$03C7	$3AFF			XORLW	255
$03C8	$1D03			BTFSS	STATUS, Z
$03C9	$2BDD			GOTO	ControleSerial_L_2
$03CA	$	ControleSerial_L_1:
;ControleSerial.pbas,20 :: 		PORTC.3=1
$03CA	$	ControleSerial_L_4:
$03CA	$1587			BSF	PORTC, 3
$03CB	$	ControleSerial_L_5:
;ControleSerial.pbas,21 :: 		delay_ms(15)
$03CB	$3014			MOVLW	20
$03CC	$00FB			MOVWF	STACK_11
$03CD	$30FF			MOVLW	255
$03CE	$00FA			MOVWF	STACK_10
$03CF	$0BFB			DECFSZ	STACK_11, F
$03D0	$2BD2			GOTO	$+2
$03D1	$2BD5			GOTO	$+4
$03D2	$0BFA			DECFSZ	STACK_10, F
$03D3	$2BD2			GOTO	$-1
$03D4	$2BCF			GOTO	$-5
$03D5	$306C			MOVLW	108
$03D6	$00FA			MOVWF	STACK_10
$03D7	$0BFA			DECFSZ	STACK_10, F
$03D8	$2BD7			GOTO	$-1
$03D9	$0000			NOP
$03DA	$0000			NOP
;ControleSerial.pbas,22 :: 		PORTC.3=0
$03DB	$1187			BCF	PORTC, 3
$03DC	$	ControleSerial_L_7:
;ControleSerial.pbas,23 :: 		passo=false
$03DC	$01A1			CLRF	_passo, 1
$03DD	$	ControleSerial_L_2:
;ControleSerial.pbas,24 :: 		end if
$03DD	$	ControleSerial_L_3:
;ControleSerial.pbas,26 :: 		for x=1 to cl step 1
$03DD	$3001			MOVLW	1
$03DE	$00C5			MOVWF	_ciclo_local_x
$03DF	$01C6			CLRF	_ciclo_local_x+1
$03E0	$	ControleSerial_L_8:
$03E0	$3080			MOVLW	128
$03E1	$0642			XORWF	FARG_ciclo+1, 0
$03E2	$00F0			MOVWF	STACK_0
$03E3	$3080			MOVLW	128
$03E4	$0646			XORWF	_ciclo_local_x+1, 0
$03E5	$0270			SUBWF	STACK_0, 0
$03E6	$1D03			BTFSS	STATUS, Z
$03E7	$2BEA			GOTO	L_ciclo_0
$03E8	$0845			MOVF	_ciclo_local_x, 0
$03E9	$0241			SUBWF	FARG_ciclo, 0
$03EA	$	L_ciclo_0:
$03EA	$1C03			BTFSS	STATUS, C
$03EB	$2C1E			GOTO	ControleSerial_L_11
;ControleSerial.pbas,27 :: 		if sentAntHor=true then
$03EC	$0822			MOVF	_sentanthor, 0
$03ED	$3AFF			XORLW	255
$03EE	$1D03			BTFSS	STATUS, Z
$03EF	$2BF1			GOTO	ControleSerial_L_13
$03F0	$	ControleSerial_L_12:
;ControleSerial.pbas,28 :: 		PORTC.2=1
$03F0	$	ControleSerial_L_15:
$03F0	$1507			BSF	PORTC, 2
$03F1	$	ControleSerial_L_16:
$03F1	$	ControleSerial_L_13:
;ControleSerial.pbas,29 :: 		end if
$03F1	$	ControleSerial_L_14:
;ControleSerial.pbas,30 :: 		setbit(PORTC, valPorta)
$03F1	$3001			MOVLW	1
$03F2	$00F0			MOVWF	STACK_0
$03F3	$0843			MOVF	FARG_ciclo+2, 0
$03F4	$	L_ciclo_1:
$03F4	$1903			BTFSC	STATUS, Z
$03F5	$2BFA			GOTO	L_ciclo_2
$03F6	$0DF0			RLF	STACK_0, 1
$03F7	$1070			BCF	STACK_0, 0
$03F8	$3FFF			ADDLW	255
$03F9	$2BF4			GOTO	L_ciclo_1
$03FA	$	L_ciclo_2:
$03FA	$0870			MOVF	STACK_0, 0
$03FB	$0487			IORWF	PORTC, 1
;ControleSerial.pbas,31 :: 		vdelay_ms(tmpOn)
$03FC	$0823			MOVF	_tmpon, 0
$03FD	$00CE			MOVWF	FARG_VDelay_ms
$03FE	$0824			MOVF	_tmpon+1, 0
$03FF	$00CF			MOVWF	FARG_VDelay_ms+1
$0400	$233C			CALL	_vdelay_ms
;ControleSerial.pbas,32 :: 		clearbit(PORTC, valPorta)
$0401	$3001			MOVLW	1
$0402	$00F0			MOVWF	STACK_0
$0403	$0843			MOVF	FARG_ciclo+2, 0
$0404	$	L_ciclo_3:
$0404	$1903			BTFSC	STATUS, Z
$0405	$2C0A			GOTO	L_ciclo_4
$0406	$0DF0			RLF	STACK_0, 1
$0407	$1070			BCF	STACK_0, 0
$0408	$3FFF			ADDLW	255
$0409	$2C04			GOTO	L_ciclo_3
$040A	$	L_ciclo_4:
$040A	$09F0			COMF	STACK_0, F
$040B	$0870			MOVF	STACK_0, 0
$040C	$0587			ANDWF	PORTC, 1
;ControleSerial.pbas,33 :: 		vdelay_ms(tmpOff)
$040D	$0825			MOVF	_tmpoff, 0
$040E	$00CE			MOVWF	FARG_VDelay_ms
$040F	$0826			MOVF	_tmpoff+1, 0
$0410	$00CF			MOVWF	FARG_VDelay_ms+1
$0411	$233C			CALL	_vdelay_ms
;ControleSerial.pbas,34 :: 		next x
$0412	$0846			MOVF	_ciclo_local_x+1, 0
$0413	$0642			XORWF	FARG_ciclo+1, 0
$0414	$1D03			BTFSS	STATUS, Z
$0415	$2C18			GOTO	L_ciclo_5
$0416	$0841			MOVF	FARG_ciclo, 0
$0417	$0645			XORWF	_ciclo_local_x, 0
$0418	$	L_ciclo_5:
$0418	$1903			BTFSC	STATUS, Z
$0419	$2C1E			GOTO	ControleSerial_L_11
$041A	$	ControleSerial_L_9:
$041A	$0AC5			INCF	_ciclo_local_x, 1
$041B	$1903			BTFSC	STATUS, Z
$041C	$0AC6			INCF	_ciclo_local_x+1, 1
$041D	$2BE0			GOTO	ControleSerial_L_8
$041E	$	ControleSerial_L_11:
;ControleSerial.pbas,36 :: 		sentAntHor = false
$041E	$01A2			CLRF	_sentanthor, 1
;ControleSerial.pbas,37 :: 		PORTC.2 = 0
$041F	$1107			BCF	PORTC, 2
$0420	$	ControleSerial_L_18:
;ControleSerial.pbas,38 :: 		delay_ms(10)
$0420	$300D			MOVLW	13
$0421	$00FB			MOVWF	STACK_11
$0422	$30FF			MOVLW	255
$0423	$00FA			MOVWF	STACK_10
$0424	$0BFB			DECFSZ	STACK_11, F
$0425	$2C27			GOTO	$+2
$0426	$2C2A			GOTO	$+4
$0427	$0BFA			DECFSZ	STACK_10, F
$0428	$2C27			GOTO	$-1
$0429	$2C24			GOTO	$-5
$042A	$30F3			MOVLW	243
$042B	$00FA			MOVWF	STACK_10
$042C	$0BFA			DECFSZ	STACK_10, F
$042D	$2C2C			GOTO	$-1
$042E	$0000			NOP
;ControleSerial.pbas,40 :: 		Usart_Write_Text(recMotor)
$042F	$3027			MOVLW	_recmotor
$0430	$00CE			MOVWF	FARG_Usart_Write_Text
$0431	$2627			CALL	_usart_write_text
;ControleSerial.pbas,41 :: 		Usart_Write_Text("end/")
$0432	$3065			MOVLW	101
$0433	$00C7			MOVWF	?ciclo_Local_Text+0
$0434	$306E			MOVLW	110
$0435	$00C8			MOVWF	?ciclo_Local_Text+1
$0436	$3064			MOVLW	100
$0437	$00C9			MOVWF	?ciclo_Local_Text+2
$0438	$302F			MOVLW	47
$0439	$00CA			MOVWF	?ciclo_Local_Text+3
$043A	$01CB			CLRF	?ciclo_Local_Text+4
$043B	$3047			MOVLW	?ciclo_Local_Text
$043C	$00CE			MOVWF	FARG_Usart_Write_Text
$043D	$2627			CALL	_usart_write_text
$043E	$	ControleSerial_L_0:
$043E	$0008			RETURN
$063D	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$063D	$	USART_b75_L_1:
$063D	$1303			BCF	STATUS, RP1
$063E	$1683			BSF	STATUS, RP0
$063F	$1698			BSF	TXSTA, 5
$0640	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$0640	$3090			MOVLW	144
$0641	$1283			BCF	STATUS, RP0
$0642	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$0643	$	USART_b75_L_3:
$0643	$1683			BSF	STATUS, RP0
$0644	$1686			BSF	TRISB, 5
$0645	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$0645	$	USART_b75_L_5:
$0645	$1786			BSF	TRISB, 7
$0646	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$0646	$	USART_b75_L_8:
$0646	$1283			BCF	STATUS, RP0
$0647	$080C			MOVF	PIR1, 0
$0648	$00F1			MOVWF	STACK_1
$0649	$3000			MOVLW	0
$064A	$1AF1			BTFSC	STACK_1, 5
$064B	$3001			MOVLW	1
$064C	$00F1			MOVWF	STACK_1
$064D	$0871			MOVF	STACK_1, 0
$064E	$3A01			XORLW	1
$064F	$1903			BTFSC	STATUS, Z
$0650	$2E46			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$0651	$	USART_b75_L_9:
$0651	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$0651	$0008			RETURN
$043F	$	_div_16x16_s:
$043F	$1303			BCF	STATUS, RP1
$0440	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$0441	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$0442	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$0443	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$0444	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$0445	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$0446	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$0447	$3400			RETLW	0
;math.ppas,356 :: 		
$0448	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$0449	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$044A	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$044B	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$044C	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$044D	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$044E	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$044F	$2C55			GOTO	$+6
;math.ppas,367 :: 		
$0450	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$0451	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$0452	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$0453	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$0454	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$0455	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$0456	$2C5C			GOTO	$+6
;math.ppas,376 :: 		
$0457	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$0458	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$0459	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$045A	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$045B	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$045C	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$045D	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$045E	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$045F	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$0460	$2C71			GOTO	$+17
;math.ppas,388 :: 		
$0461	$25DD			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$0462	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$0463	$2C84			GOTO	$+33
;math.ppas,393 :: 		
$0464	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$0465	$3400			RETLW	0
;math.ppas,396 :: 		
$0466	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$0467	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$0468	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$0469	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$046A	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$046B	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$046C	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$046D	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$046E	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$046F	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$0470	$3400			RETLW	0
;math.ppas,410 :: 		
$0471	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$0472	$2C80			GOTO	$+14
;math.ppas,412 :: 		
$0473	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$0474	$2C7C			GOTO	$+8
;math.ppas,414 :: 		
$0475	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$0476	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$0477	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$0478	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$0479	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$047A	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$047B	$2C64			GOTO	$-23
;math.ppas,421 :: 		
$047C	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$047D	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$047E	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$047F	$3400			RETLW	0
;math.ppas,426 :: 		
$0480	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$0481	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$0482	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$0483	$2C61			GOTO	$-34
;math.ppas,431 :: 		
$0484	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$0485	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$0486	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$0487	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$0488	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$0489	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$048A	$2C64			GOTO	$-38
;math.ppas,438 :: 		
$048B	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$048C	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$048D	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$048E	$2C64			GOTO	$-42
;math.ppas,442 :: 		
$048F	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$0490	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$0491	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$0492	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$0493	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$0494	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$0495	$2C64			GOTO	$-49
;math.ppas,449 :: 		
$0496	$0000			NOP
;math.ppas,450 :: 		
$0497	$34FF			RETLW	255
;math.ppas,451 :: 		
$0498	$	math_L_7:
;math.ppas,452 :: 		
$0498	$0008			RETURN
$04DC	$	_mul_16x16_s:
$04DC	$1303			BCF	STATUS, RP1
$04DD	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$04DE	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$04DF	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$04E0	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$04E1	$3080			MOVLW	128
;math.ppas,210 :: 		
$04E2	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$04E3	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$04E4	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$04E5	$2CEC			GOTO	$+7
;math.ppas,215 :: 		
$04E6	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$04E7	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$04E8	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$04E9	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$04EA	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$04EB	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$04EC	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$04ED	$2CF4			GOTO	$+7
;math.ppas,224 :: 		
$04EE	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$04EF	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$04F0	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$04F1	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$04F2	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$04F3	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$04F4	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$04F5	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$04F6	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$04F7	$2D01			GOTO	$+10
;math.ppas,236 :: 		
$04F8	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$04F9	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$04FA	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$04FB	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$04FC	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$04FD	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$04FE	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$04FF	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$0500	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$0501	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$0502	$2D09			GOTO	$+7
;math.ppas,249 :: 		
$0503	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$0504	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$0505	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$0506	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$0507	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$0508	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$0509	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$050A	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$050B	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$050C	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$050D	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$050E	$2CF4			GOTO	$-26
;math.ppas,263 :: 		
$050F	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$0510	$2D1C			GOTO	$+12
;math.ppas,266 :: 		
$0511	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$0512	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$0513	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$0514	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$0515	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$0516	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$0517	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$0518	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$0519	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$051A	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$051B	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$051C	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$051D	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$051E	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$051F	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$0520	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$0521	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$0522	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$0523	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$0524	$	math_L_5:
;math.ppas,288 :: 		
$0524	$0008			RETURN
$0132	$	_main:
;ControleSerial.pbas,45 :: 		main:
$0132	$	_main_main:
;ControleSerial.pbas,46 :: 		TRISA=%11111111
$0132	$30FF			MOVLW	255
$0133	$1303			BCF	STATUS, RP1
$0134	$1683			BSF	STATUS, RP0
$0135	$0085			MOVWF	TRISA
;ControleSerial.pbas,47 :: 		TRISB=%01111111
$0136	$307F			MOVLW	127
$0137	$0086			MOVWF	TRISB
;ControleSerial.pbas,48 :: 		TRISC=%00000000
$0138	$0187			CLRF	TRISC, 1
;ControleSerial.pbas,49 :: 		INTCON=%00000000
$0139	$018B			CLRF	INTCON, 1
;ControleSerial.pbas,50 :: 		ANSEL=%00000000
$013A	$1703			BSF	STATUS, RP1
$013B	$1283			BCF	STATUS, RP0
$013C	$019E			CLRF	ANSEL, 1
;ControleSerial.pbas,51 :: 		ANSELH=%00000000
$013D	$019F			CLRF	ANSELH, 1
;ControleSerial.pbas,53 :: 		PORTC=0
$013E	$1303			BCF	STATUS, RP1
$013F	$0187			CLRF	PORTC, 1
;ControleSerial.pbas,55 :: 		tmpOn=25
$0140	$3019			MOVLW	25
$0141	$00A3			MOVWF	_tmpon
$0142	$01A4			CLRF	_tmpon+1
;ControleSerial.pbas,56 :: 		tmpOff=25
$0143	$3019			MOVLW	25
$0144	$00A5			MOVWF	_tmpoff
$0145	$01A6			CLRF	_tmpoff+1
;ControleSerial.pbas,58 :: 		sentAntHor=false 'Inicia em sentido horário
$0146	$01A2			CLRF	_sentanthor, 1
;ControleSerial.pbas,59 :: 		passo=false      'Inicia em passos de 3.75
$0147	$01A1			CLRF	_passo, 1
;ControleSerial.pbas,61 :: 		Usart_Init(9600)
$0148	$3019			MOVLW	25
$0149	$1683			BSF	STATUS, RP0
$014A	$0099			MOVWF	SPBRG
$014B	$1518			BSF	TXSTA, BRGH
$014C	$263D			CALL	_usart_init
;ControleSerial.pbas,63 :: 		executa:
$014D	$	_main_executa:
;ControleSerial.pbas,64 :: 		if Usart_Data_Ready() then
$014D	$2685			CALL	_usart_data_ready
$014E	$0870			MOVF	STACK_0, 0
$014F	$1903			BTFSC	STATUS, Z
$0150	$29DE			GOTO	ControleSerial_L_21
$0151	$	ControleSerial_L_20:
;ControleSerial.pbas,65 :: 		Usart_Read_Text(recMotor,"\")
$0151	$3027			MOVLW	_recmotor
$0152	$00C1			MOVWF	FARG_Usart_Read_Text
$0153	$305C			MOVLW	92
$0154	$00BB			MOVWF	?main_Local_Text+0
$0155	$01BC			CLRF	?main_Local_Text+1
$0156	$303B			MOVLW	?main_Local_Text
$0157	$00C2			MOVWF	FARG_Usart_Read_Text+1
$0158	$2499			CALL	_usart_read_text
;ControleSerial.pbas,66 :: 		Usart_Read_Text(recDirec,"/")
$0159	$302E			MOVLW	_recdirec
$015A	$00C1			MOVWF	FARG_Usart_Read_Text
$015B	$302F			MOVLW	47
$015C	$00BB			MOVWF	?main_Local_Text+0
$015D	$01BC			CLRF	?main_Local_Text+1
$015E	$303B			MOVLW	?main_Local_Text
$015F	$00C2			MOVWF	FARG_Usart_Read_Text+1
$0160	$2499			CALL	_usart_read_text
;ControleSerial.pbas,67 :: 		valor = StrToInt(recMotor)
$0161	$3027			MOVLW	_recmotor
$0162	$00C1			MOVWF	FARG_StrToInt
$0163	$21E0			CALL	_strtoint
$0164	$0870			MOVF	STACK_0, 0
$0165	$00B5			MOVWF	_valor
$0166	$0871			MOVF	STACK_0+1, 0
$0167	$00B6			MOVWF	_valor+1
;ControleSerial.pbas,69 :: 		if strcmp(recDirec, "inv") = 0 then  'Determina a mudança de direção.
$0168	$302E			MOVLW	_recdirec
$0169	$00C1			MOVWF	FARG_strcmp
$016A	$3069			MOVLW	105
$016B	$00BB			MOVWF	?main_Local_Text+0
$016C	$306E			MOVLW	110
$016D	$00BC			MOVWF	?main_Local_Text+1
$016E	$3076			MOVLW	118
$016F	$00BD			MOVWF	?main_Local_Text+2
$0170	$01BE			CLRF	?main_Local_Text+3
$0171	$303B			MOVLW	?main_Local_Text
$0172	$00C2			MOVWF	FARG_strcmp+1
$0173	$2525			CALL	_strcmp
$0174	$3000			MOVLW	0
$0175	$0671			XORWF	STACK_0+1, 0
$0176	$1D03			BTFSS	STATUS, Z
$0177	$297A			GOTO	L_main_6
$0178	$3000			MOVLW	0
$0179	$0670			XORWF	STACK_0, 0
$017A	$	L_main_6:
$017A	$1D03			BTFSS	STATUS, Z
$017B	$297E			GOTO	ControleSerial_L_24
$017C	$	ControleSerial_L_23:
;ControleSerial.pbas,70 :: 		sentAntHor=true
$017C	$30FF			MOVLW	255
$017D	$00A2			MOVWF	_sentanthor
$017E	$	ControleSerial_L_24:
;ControleSerial.pbas,71 :: 		end if
$017E	$	ControleSerial_L_25:
;ControleSerial.pbas,73 :: 		if strcmp(recDirec, "nor") = 0 then
$017E	$302E			MOVLW	_recdirec
$017F	$00C1			MOVWF	FARG_strcmp
$0180	$306E			MOVLW	110
$0181	$00BB			MOVWF	?main_Local_Text+0
$0182	$306F			MOVLW	111
$0183	$00BC			MOVWF	?main_Local_Text+1
$0184	$3072			MOVLW	114
$0185	$00BD			MOVWF	?main_Local_Text+2
$0186	$01BE			CLRF	?main_Local_Text+3
$0187	$303B			MOVLW	?main_Local_Text
$0188	$00C2			MOVWF	FARG_strcmp+1
$0189	$2525			CALL	_strcmp
$018A	$3000			MOVLW	0
$018B	$0671			XORWF	STACK_0+1, 0
$018C	$1D03			BTFSS	STATUS, Z
$018D	$2990			GOTO	L_main_7
$018E	$3000			MOVLW	0
$018F	$0670			XORWF	STACK_0, 0
$0190	$	L_main_7:
$0190	$1D03			BTFSS	STATUS, Z
$0191	$2993			GOTO	ControleSerial_L_27
$0192	$	ControleSerial_L_26:
;ControleSerial.pbas,74 :: 		sentAntHor=false
$0192	$01A2			CLRF	_sentanthor, 1
$0193	$	ControleSerial_L_27:
;ControleSerial.pbas,75 :: 		end if
$0193	$	ControleSerial_L_28:
;ControleSerial.pbas,77 :: 		motor = valor div 1000
$0193	$30E8			MOVLW	232
$0194	$00F4			MOVWF	STACK_4
$0195	$3003			MOVLW	3
$0196	$00F5			MOVWF	STACK_4+1
$0197	$0835			MOVF	_valor, 0
$0198	$00F0			MOVWF	STACK_0
$0199	$0836			MOVF	_valor+1, 0
$019A	$00F1			MOVWF	STACK_0+1
$019B	$243F			CALL	_div_16x16_s
$019C	$0870			MOVF	STACK_0, 0
$019D	$00BF			MOVWF	FLOC_main+4
$019E	$0871			MOVF	STACK_0+1, 0
$019F	$00C0			MOVWF	FLOC_main+5
$01A0	$083F			MOVF	FLOC_main+4, 0
$01A1	$00B7			MOVWF	_motor
$01A2	$0840			MOVF	FLOC_main+5, 0
$01A3	$00B8			MOVWF	_motor+1
;ControleSerial.pbas,78 :: 		ciclos = valor - (motor * 1000)
$01A4	$083F			MOVF	FLOC_main+4, 0
$01A5	$00F0			MOVWF	STACK_0
$01A6	$0840			MOVF	FLOC_main+5, 0
$01A7	$00F1			MOVWF	STACK_0+1
$01A8	$30E8			MOVLW	232
$01A9	$00F4			MOVWF	STACK_4
$01AA	$3003			MOVLW	3
$01AB	$00F5			MOVWF	STACK_4+1
$01AC	$24DC			CALL	_mul_16x16_s
$01AD	$0870			MOVF	STACK_0, 0
$01AE	$0235			SUBWF	_valor, 0
$01AF	$00B9			MOVWF	_ciclos
$01B0	$0871			MOVF	STACK_0+1, 0
$01B1	$1C03			BTFSS	STATUS, C
$01B2	$3F01			ADDLW	1
$01B3	$0236			SUBWF	_valor+1, 0
$01B4	$00BA			MOVWF	_ciclos+1
;ControleSerial.pbas,80 :: 		if motor=1 then 'Envia o número de pulsos.
$01B5	$3000			MOVLW	0
$01B6	$0640			XORWF	FLOC_main+5, 0
$01B7	$1D03			BTFSS	STATUS, Z
$01B8	$29BB			GOTO	L_main_8
$01B9	$3001			MOVLW	1
$01BA	$063F			XORWF	FLOC_main+4, 0
$01BB	$	L_main_8:
$01BB	$1D03			BTFSS	STATUS, Z
$01BC	$29C4			GOTO	ControleSerial_L_30
$01BD	$	ControleSerial_L_29:
;ControleSerial.pbas,81 :: 		ciclo(ciclos, 0)
$01BD	$0839			MOVF	_ciclos, 0
$01BE	$00C1			MOVWF	FARG_ciclo
$01BF	$083A			MOVF	_ciclos+1, 0
$01C0	$00C2			MOVWF	FARG_ciclo+1
$01C1	$01C3			CLRF	FARG_ciclo+2
$01C2	$01C4			CLRF	FARG_ciclo+3
$01C3	$23C4			CALL	_ciclo
$01C4	$	ControleSerial_L_30:
;ControleSerial.pbas,82 :: 		end if
$01C4	$	ControleSerial_L_31:
;ControleSerial.pbas,84 :: 		if motor=2 then 'Envia o número de pulsos.
$01C4	$3000			MOVLW	0
$01C5	$0638			XORWF	_motor+1, 0
$01C6	$1D03			BTFSS	STATUS, Z
$01C7	$29CA			GOTO	L_main_9
$01C8	$3002			MOVLW	2
$01C9	$0637			XORWF	_motor, 0
$01CA	$	L_main_9:
$01CA	$1D03			BTFSS	STATUS, Z
$01CB	$29D4			GOTO	ControleSerial_L_33
$01CC	$	ControleSerial_L_32:
;ControleSerial.pbas,85 :: 		ciclo(ciclos, 1)
$01CC	$0839			MOVF	_ciclos, 0
$01CD	$00C1			MOVWF	FARG_ciclo
$01CE	$083A			MOVF	_ciclos+1, 0
$01CF	$00C2			MOVWF	FARG_ciclo+1
$01D0	$3001			MOVLW	1
$01D1	$00C3			MOVWF	FARG_ciclo+2
$01D2	$01C4			CLRF	FARG_ciclo+3
$01D3	$23C4			CALL	_ciclo
$01D4	$	ControleSerial_L_33:
;ControleSerial.pbas,86 :: 		end if
$01D4	$	ControleSerial_L_34:
;ControleSerial.pbas,88 :: 		if valor=1002 then  'Determina a mudança W/H.
$01D4	$0836			MOVF	_valor+1, 0
$01D5	$3A03			XORLW	3
$01D6	$1D03			BTFSS	STATUS, Z
$01D7	$29DA			GOTO	L_main_10
$01D8	$30EA			MOVLW	234
$01D9	$0635			XORWF	_valor, 0
$01DA	$	L_main_10:
$01DA	$1D03			BTFSS	STATUS, Z
$01DB	$29DE			GOTO	ControleSerial_L_36
$01DC	$	ControleSerial_L_35:
;ControleSerial.pbas,89 :: 		passo=true
$01DC	$30FF			MOVLW	255
$01DD	$00A1			MOVWF	_passo
$01DE	$	ControleSerial_L_36:
;ControleSerial.pbas,90 :: 		end if
$01DE	$	ControleSerial_L_37:
$01DE	$	ControleSerial_L_21:
;ControleSerial.pbas,92 :: 		end if
$01DE	$	ControleSerial_L_22:
;ControleSerial.pbas,94 :: 		goto executa
$01DE	$294D			GOTO	_main_executa
$01DF	$29DF			GOTO	$
