;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 22/10/2020 22:12:12
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2B16			GOTO	_main
$0442	$	_mul_32x32_u:
$0442	$1303			BCF	STATUS, RP1
$0443	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$0444	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0445	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$0446	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$0447	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$0448	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$0449	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$044A	$	_NEXT:
;math.ppas,1589 :: 		
$044A	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$044B	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$044C	$2C78			GOTO	_EXIT2
;math.ppas,1593 :: 		
$044D	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$044E	$	_LOOP:
;math.ppas,1603 :: 		
$044E	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$044F	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$0450	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$0451	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$0452	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$0453	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$0454	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0455	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$0456	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$0457	$2C4A			GOTO	_NEXT
;math.ppas,1617 :: 		
$0458	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$0459	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$045A	$2C6A			GOTO	_EXIT1
;math.ppas,1626 :: 		
$045B	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$045C	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$045D	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$045E	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$045F	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$0460	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$0461	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$0462	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$0463	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0464	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0465	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0466	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$0467	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$0468	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$0469	$2C4E			GOTO	_LOOP
;math.ppas,1647 :: 		
$046A	$	_EXIT1:
;math.ppas,1648 :: 		
$046A	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$046B	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$046C	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$046D	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$046E	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$046F	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$0470	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$0471	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$0472	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$0473	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0474	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0475	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0476	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$0477	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$0478	$	_EXIT2:
;math.ppas,1665 :: 		
$0478	$	math_L_13:
;math.ppas,1666 :: 		
$0478	$0008			RETURN
$0004	$	_sdiv3232l:
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0006	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0007	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0008	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0009	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$000A	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$000B	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$000C	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$000D	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$000E	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$000F	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0010	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0011	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0012	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0013	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0014	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0015	$3007			MOVLW	7
;math.ppas,559 :: 		
$0016	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0017	$	LOOPS3232A:
;math.ppas,561 :: 		
$0017	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0018	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0019	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$001A	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$001B	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$001C	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$001D	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$001E	$282D			GOTO	SADD22LA
;math.ppas,570 :: 		
$001F	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0020	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0021	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0022	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0023	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0024	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0025	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0026	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0027	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0028	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0029	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$002A	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$002B	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$002C	$283A			GOTO	SOK22LA
;math.ppas,585 :: 		
$002D	$	SADD22LA:
;math.ppas,586 :: 		
$002D	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$002E	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$002F	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0030	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0031	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0032	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0033	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0034	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0035	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0036	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0037	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0038	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0039	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$003A	$	SOK22LA:
;math.ppas,602 :: 		
$003A	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$003B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$003C	$2817			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$003D	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$003E	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$003F	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0040	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0041	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0042	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0043	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0044	$2853			GOTO	SADD22L8
;math.ppas,615 :: 		
$0045	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0046	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0047	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0048	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0049	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$004A	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$004B	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$004C	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$004D	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$004E	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$004F	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0050	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0051	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0052	$2860			GOTO	SOK22L8
;math.ppas,630 :: 		
$0053	$	SADD22L8:
;math.ppas,631 :: 		
$0053	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0054	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0055	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0056	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0057	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0058	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0059	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$005A	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$005B	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$005C	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$005D	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$005E	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$005F	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0060	$	SOK22L8:
;math.ppas,647 :: 		
$0060	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0061	$3007			MOVLW	7
;math.ppas,650 :: 		
$0062	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0063	$	LOOPS3232B:
;math.ppas,652 :: 		
$0063	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0064	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0065	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0066	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0067	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0068	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0069	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$006A	$2879			GOTO	SADD22LB
;math.ppas,661 :: 		
$006B	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$006C	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$006D	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$006E	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$006F	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$0070	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0071	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0072	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0073	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0074	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0075	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0076	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0077	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0078	$2886			GOTO	SOK22LB
;math.ppas,676 :: 		
$0079	$	SADD22LB:
;math.ppas,677 :: 		
$0079	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$007A	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$007B	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$007C	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$007D	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$007E	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$007F	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$0080	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$0081	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$0082	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$0083	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$0084	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$0085	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$0086	$	SOK22LB:
;math.ppas,693 :: 		
$0086	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$0087	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$0088	$2863			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$0089	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$008A	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$008B	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$008C	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$008D	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$008E	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$008F	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$0090	$289F			GOTO	SADD22L16
;math.ppas,706 :: 		
$0091	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$0092	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$0093	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0094	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$0095	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$0096	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0097	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0098	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$0099	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$009A	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$009B	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$009C	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$009D	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$009E	$28AC			GOTO	SOK22L16
;math.ppas,721 :: 		
$009F	$	SADD22L16:
;math.ppas,722 :: 		
$009F	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$00A0	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$00A1	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$00A2	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$00A3	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$00A4	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$00A5	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$00A6	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$00A7	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$00A8	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$00A9	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$00AA	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$00AB	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$00AC	$	SOK22L16:
;math.ppas,738 :: 		
$00AC	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$00AD	$3007			MOVLW	7
;math.ppas,741 :: 		
$00AE	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$00AF	$	LOOPS3232C:
;math.ppas,743 :: 		
$00AF	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$00B0	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$00B1	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$00B2	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$00B3	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$00B4	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$00B5	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$00B6	$28C5			GOTO	SADD22LC
;math.ppas,752 :: 		
$00B7	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$00B8	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$00B9	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$00BA	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$00BB	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$00BC	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$00BD	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$00BE	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$00BF	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$00C0	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$00C1	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$00C2	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$00C3	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$00C4	$28D2			GOTO	SOK22LC
;math.ppas,767 :: 		
$00C5	$	SADD22LC:
;math.ppas,768 :: 		
$00C5	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$00C6	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$00C7	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$00C8	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$00C9	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$00CA	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$00CB	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$00CC	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$00CD	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$00CE	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$00CF	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$00D0	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$00D1	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$00D2	$	SOK22LC:
;math.ppas,784 :: 		
$00D2	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$00D3	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$00D4	$28AF			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$00D5	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$00D6	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$00D7	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$00D8	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$00D9	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$00DA	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$00DB	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$00DC	$28EB			GOTO	SADD22L24
;math.ppas,797 :: 		
$00DD	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$00DE	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$00DF	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$00E0	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$00E1	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$00E2	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$00E3	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$00E4	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$00E5	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$00E6	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$00E7	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$00E8	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$00E9	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$00EA	$28F8			GOTO	SOK22L24
;math.ppas,812 :: 		
$00EB	$	SADD22L24:
;math.ppas,813 :: 		
$00EB	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$00EC	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$00ED	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$00EE	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$00EF	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$00F0	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$00F1	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$00F2	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$00F3	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$00F4	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$00F5	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$00F6	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$00F7	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$00F8	$	SOK22L24:
;math.ppas,829 :: 		
$00F8	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$00F9	$3007			MOVLW	7
;math.ppas,832 :: 		
$00FA	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$00FB	$	LOOPS3232D:
;math.ppas,834 :: 		
$00FB	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$00FC	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$00FD	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$00FE	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$00FF	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0100	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0101	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0102	$2911			GOTO	SADD22LD
;math.ppas,843 :: 		
$0103	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0104	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0105	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0106	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0107	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0108	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0109	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$010A	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$010B	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$010C	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$010D	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$010E	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$010F	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0110	$291E			GOTO	SOK22LD
;math.ppas,858 :: 		
$0111	$	SADD22LD:
;math.ppas,859 :: 		
$0111	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0112	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0113	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0114	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0115	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0116	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0117	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0118	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0119	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$011A	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$011B	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$011C	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$011D	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$011E	$	SOK22LD:
;math.ppas,876 :: 		
$011E	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$011F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0120	$28FB			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0121	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0122	$2931			GOTO	SOK22L
;math.ppas,882 :: 		
$0123	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0124	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0125	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0126	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0127	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0128	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0129	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$012A	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$012B	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$012C	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$012D	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$012E	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$012F	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0130	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0131	$	SOK22L:
;math.ppas,897 :: 		
$0131	$	math_L_9:
;math.ppas,898 :: 		
$0131	$0008			RETURN
$04E6	$	_comfrem:
$04E6	$1303			BCF	STATUS, RP1
$04E7	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$04E8	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$04E9	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$04EA	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$04EB	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$04EC	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$04ED	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$04EE	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$04EF	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$04F0	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$04F1	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$04F2	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$04F3	$	math_L_10:
;math.ppas,915 :: 		
$04F3	$0008			RETURN
$04F4	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$04F4	$1303			BCF	STATUS, RP1
$04F5	$1283			BCF	STATUS, RP0
$04F6	$080C			MOVF	PIR1, 0
$04F7	$00F1			MOVWF	STACK_1
$04F8	$3000			MOVLW	0
$04F9	$1AF1			BTFSC	STACK_1, 5
$04FA	$3001			MOVLW	1
$04FB	$00F1			MOVWF	STACK_1
$04FC	$0871			MOVF	STACK_1, 0
$04FD	$00BF			MOVWF	_usart_data_ready_local_result
$04FE	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$04FE	$083F			MOVF	_usart_data_ready_local_result, 0
$04FF	$00F0			MOVWF	STACK_0
$0500	$0008			RETURN
$04C1	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$04C1	$1303			BCF	STATUS, RP1
$04C2	$1283			BCF	STATUS, RP0
$04C3	$081A			MOVF	RCREG, 0
$04C4	$00BF			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$04C5	$0818			MOVF	RCSTA, 0
$04C6	$00F1			MOVWF	STACK_1
$04C7	$3000			MOVLW	0
$04C8	$18F1			BTFSC	STACK_1, 1
$04C9	$3001			MOVLW	1
$04CA	$00F1			MOVWF	STACK_1
$04CB	$0871			MOVF	STACK_1, 0
$04CC	$3A01			XORLW	1
$04CD	$1D03			BTFSS	STATUS, Z
$04CE	$2CD1			GOTO	USART_b75_L_21
$04CF	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$04CF	$1218			BCF	RCSTA, 4
$04D0	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$04D0	$	USART_b75_L_25:
$04D0	$1618			BSF	RCSTA, 4
$04D1	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$04D1	$	USART_b75_L_21:
$04D1	$	USART_b75_L_22:
$04D1	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$04D1	$083F			MOVF	_usart_read_local_result, 0
$04D2	$00F0			MOVWF	STACK_0
$04D3	$0008			RETURN
$04D4	$	_usart_write:
;USART_b75.ppas,40 :: 		
;USART_b75.ppas,42 :: 		
$04D4	$	USART_b75_L_14:
$04D4	$1303			BCF	STATUS, RP1
$04D5	$1683			BSF	STATUS, RP0
$04D6	$0818			MOVF	TXSTA, 0
$04D7	$00F1			MOVWF	STACK_1
$04D8	$3000			MOVLW	0
$04D9	$18F1			BTFSC	STACK_1, 1
$04DA	$3001			MOVLW	1
$04DB	$00F1			MOVWF	STACK_1
$04DC	$0871			MOVF	STACK_1, 0
$04DD	$3A00			XORLW	0
$04DE	$1D03			BTFSS	STATUS, Z
$04DF	$2CE2			GOTO	USART_b75_L_15
;USART_b75.ppas,43 :: 		
$04E0	$0000			NOP
$04E1	$2CD4			GOTO	USART_b75_L_14
$04E2	$	USART_b75_L_15:
;USART_b75.ppas,44 :: 		
$04E2	$1283			BCF	STATUS, RP0
$04E3	$083F			MOVF	FARG_USART_Write, 0
$04E4	$0099			MOVWF	TXREG
$04E5	$	USART_b75_L_12:
;USART_b75.ppas,45 :: 		
$04E5	$0008			RETURN
$0407	$	_mul_32x32_s:
$0407	$1303			BCF	STATUS, RP1
$0408	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$0409	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$040A	$	_IF_FIRST:
;math.ppas,1684 :: 		
$040A	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$040B	$2C19			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$040C	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$040C	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$040D	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$040E	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$040F	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$0410	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$0411	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$0412	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$0413	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$0414	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$0415	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$0416	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$0417	$3081			MOVLW	129
;math.ppas,1711 :: 		
$0418	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$0419	$	_IF_SECOND:
;math.ppas,1715 :: 		
$0419	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$041A	$2C27			GOTO	_MULT
;math.ppas,1722 :: 		
$041B	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$041B	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$041C	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$041D	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$041E	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$041F	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$0420	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$0421	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$0422	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$0423	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$0424	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$0425	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$0426	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$0427	$	_MULT:
;math.ppas,1744 :: 		
$0427	$2442			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$0428	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$0429	$2C41			GOTO	_EXIT
;math.ppas,1755 :: 		
$042A	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$042B	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$042C	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$042D	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$042E	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$042F	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$0430	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$0431	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$0432	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$0433	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$0434	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$0435	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$0436	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$0437	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$0438	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$0439	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$043A	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$043B	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$043C	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$043D	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$043E	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$043F	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$0440	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$0441	$	_EXIT:
;math.ppas,1793 :: 		
$0441	$	math_L_14:
;math.ppas,1794 :: 		
$0441	$0008			RETURN
$0479	$	_div_16x16_u:
$0479	$1303			BCF	STATUS, RP1
$047A	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$047B	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$047C	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$047D	$3010			MOVLW	16
;math.ppas,113 :: 		
$047E	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$047F	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0480	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0481	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0482	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$0483	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0484	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0485	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0486	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0487	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0488	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0489	$2C91			GOTO	$+8
;math.ppas,125 :: 		
$048A	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$048B	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$048C	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$048D	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$048E	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$048F	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0490	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0491	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$0492	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$0493	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0494	$2C7F			GOTO	$-21
;math.ppas,136 :: 		
$0495	$	math_L_3:
;math.ppas,137 :: 		
$0495	$0008			RETURN
$01F4	$	_div_32x32_s:
$01F4	$1303			BCF	STATUS, RP1
$01F5	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$01F6	$	FXD3232S:
;math.ppas,929 :: 		
$01F6	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$01F7	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$01F8	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$01F9	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$01FA	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$01FB	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$01FC	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$01FD	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$01FE	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$01FF	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0200	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0201	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0202	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0203	$2A88			GOTO	END_ALL
;math.ppas,944 :: 		
$0204	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0205	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0206	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0207	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0208	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0209	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$020A	$2A16			GOTO	CA3232S
;math.ppas,955 :: 		
$020B	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$020C	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$020D	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$020E	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$020F	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0210	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0211	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0212	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0213	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0214	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0215	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0216	$	CA3232S:
;math.ppas,968 :: 		
$0216	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0217	$2A23			GOTO	C3232SX
;math.ppas,971 :: 		
$0218	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0219	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$021A	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$021B	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$021C	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$021D	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$021E	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$021F	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0220	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0221	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0222	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0223	$	C3232SX:
;math.ppas,984 :: 		
$0223	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0224	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$0225	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0226	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0227	$2A44			GOTO	C3232SX1
;math.ppas,989 :: 		
$0228	$	C3232S:
;math.ppas,992 :: 		
$0228	$2004			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0229	$	C3232S2:
;math.ppas,996 :: 		
$0229	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$022A	$2A61			GOTO	C3232SX4
;math.ppas,998 :: 		
$022B	$	C3232SOK:
;math.ppas,999 :: 		
$022B	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$022C	$2A88			GOTO	END_ALL
;math.ppas,1001 :: 		
$022D	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$022E	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$022F	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0230	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0231	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0232	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0233	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0234	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$0235	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0236	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0237	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0238	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0239	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$023A	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$023B	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$023C	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$023D	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$023E	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$023F	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0240	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0241	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0242	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0243	$2A88			GOTO	END_ALL
;math.ppas,1026 :: 		
$0244	$	C3232SX1:
;math.ppas,1027 :: 		
$0244	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$0245	$2A5B			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0246	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0247	$2A55			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0248	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0249	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$024A	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$024B	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$024C	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$024D	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$024E	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$024F	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0250	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0251	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0252	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0253	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0254	$2A2B			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0255	$	C3232SX2:
;math.ppas,1045 :: 		
$0255	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0256	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0257	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0258	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0259	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$025A	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$025B	$	C3232SX3:
;math.ppas,1053 :: 		
$025B	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$025C	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$025D	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$025E	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$025F	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0260	$2A28			GOTO	C3232S
;math.ppas,1061 :: 		
$0261	$	C3232SX4:
;math.ppas,1062 :: 		
$0261	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0262	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0263	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0264	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0265	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0266	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0267	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0268	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0269	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$026A	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$026B	$2A2B			GOTO	C3232SOK
;math.ppas,1073 :: 		
$026C	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$026D	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$026E	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$026F	$2A2B			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0270	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0271	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0272	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0273	$2A2B			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0274	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0275	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0276	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$0277	$2A2B			GOTO	C3232SOK
;math.ppas,1085 :: 		
$0278	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$0279	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$027A	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$027B	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$027C	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$027D	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$027E	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$027F	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0280	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0281	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0282	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0283	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0284	$2A2B			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0285	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0286	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0287	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0288	$	END_ALL:
;math.ppas,1102 :: 		
$0288	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$0289	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$028A	$2A8C			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$028B	$24E6			CALL	_comfrem
;math.ppas,1108 :: 		
$028C	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$028C	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$028D	$	math_L_11:
;math.ppas,1111 :: 		
$028D	$0008			RETURN
$028E	$	_vdelay_ms:
;delays.pbas,65 :: 		dim NumberOfCyc as dword
;delays.pbas,67 :: 		NumberOfCyc = Clock_kHz >> 2 ' this will be done by compiler, no asm will be genereated except that for assignment
$028E	$30E8			MOVLW	232
$028F	$1303			BCF	STATUS, RP1
$0290	$1283			BCF	STATUS, RP0
$0291	$00C1			MOVWF	_vdelay_ms_local_numberofcyc
$0292	$3003			MOVLW	3
$0293	$00C2			MOVWF	_vdelay_ms_local_numberofcyc+1
$0294	$01C3			CLRF	_vdelay_ms_local_numberofcyc+2
$0295	$01C4			CLRF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,68 :: 		NumberOfCyc = Time_ms * NumberOfCyc
$0296	$083F			MOVF	FARG_VDelay_ms, 0
$0297	$00F0			MOVWF	STACK_0
$0298	$0840			MOVF	FARG_VDelay_ms+1, 0
$0299	$00F1			MOVWF	STACK_0+1
$029A	$01F2			CLRF	STACK_0+2
$029B	$01F3			CLRF	STACK_0+3
$029C	$30E8			MOVLW	232
$029D	$00F4			MOVWF	STACK_4
$029E	$3003			MOVLW	3
$029F	$00F5			MOVWF	STACK_4+1
$02A0	$3000			MOVLW	0
$02A1	$00F6			MOVWF	STACK_4+2
$02A2	$3000			MOVLW	0
$02A3	$00F7			MOVWF	STACK_4+3
$02A4	$2442			CALL	_mul_32x32_u
$02A5	$0870			MOVF	STACK_0, 0
$02A6	$00C1			MOVWF	_vdelay_ms_local_numberofcyc
$02A7	$0871			MOVF	STACK_0+1, 0
$02A8	$00C2			MOVWF	_vdelay_ms_local_numberofcyc+1
$02A9	$0872			MOVF	STACK_0+2, 0
$02AA	$00C3			MOVWF	_vdelay_ms_local_numberofcyc+2
$02AB	$0873			MOVF	STACK_0+3, 0
$02AC	$00C4			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,69 :: 		if NumberOfCyc < 675 then
$02AD	$3000			MOVLW	0
$02AE	$0273			SUBWF	STACK_0+3, 0
$02AF	$1D03			BTFSS	STATUS, Z
$02B0	$2ABB			GOTO	L_VDelay_ms_0
$02B1	$3000			MOVLW	0
$02B2	$0272			SUBWF	STACK_0+2, 0
$02B3	$1D03			BTFSS	STATUS, Z
$02B4	$2ABB			GOTO	L_VDelay_ms_0
$02B5	$3002			MOVLW	2
$02B6	$0271			SUBWF	STACK_0+1, 0
$02B7	$1D03			BTFSS	STATUS, Z
$02B8	$2ABB			GOTO	L_VDelay_ms_0
$02B9	$30A3			MOVLW	163
$02BA	$0270			SUBWF	STACK_0, 0
$02BB	$	L_VDelay_ms_0:
$02BB	$1803			BTFSC	STATUS, C
$02BC	$2ABE			GOTO	delays_L_19
$02BD	$	delays_L_18:
;delays.pbas,70 :: 		exit
$02BD	$2B15			GOTO	delays_L_17
$02BE	$	delays_L_19:
;delays.pbas,71 :: 		end if
$02BE	$	delays_L_20:
;delays.pbas,72 :: 		NumberOfCyc = NumberOfCyc - 675
$02BE	$30A3			MOVLW	163
$02BF	$00F0			MOVWF	STACK_0
$02C0	$3002			MOVLW	2
$02C1	$00F1			MOVWF	STACK_0+1
$02C2	$01F2			CLRF	STACK_0+2
$02C3	$01F3			CLRF	STACK_0+3
$02C4	$0841			MOVF	_vdelay_ms_local_numberofcyc, 0
$02C5	$00F4			MOVWF	STACK_4
$02C6	$0842			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$02C7	$00F5			MOVWF	STACK_4+1
$02C8	$0843			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$02C9	$00F6			MOVWF	STACK_4+2
$02CA	$0844			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$02CB	$00F7			MOVWF	STACK_4+3
$02CC	$0870			MOVF	STACK_0, 0
$02CD	$02F4			SUBWF	STACK_4, 1
$02CE	$0871			MOVF	STACK_0+1, 0
$02CF	$1C03			BTFSS	STATUS, C
$02D0	$0F71			INCFSZ	STACK_0+1, 0
$02D1	$02F5			SUBWF	STACK_4+1, 1
$02D2	$0872			MOVF	STACK_0+2, 0
$02D3	$1C03			BTFSS	STATUS, C
$02D4	$0F72			INCFSZ	STACK_0+2, 0
$02D5	$02F6			SUBWF	STACK_4+2, 1
$02D6	$0873			MOVF	STACK_0+3, 0
$02D7	$1C03			BTFSS	STATUS, C
$02D8	$0F73			INCFSZ	STACK_0+3, 0
$02D9	$02F7			SUBWF	STACK_4+3, 1
$02DA	$0874			MOVF	STACK_4, 0
$02DB	$00C1			MOVWF	_vdelay_ms_local_numberofcyc
$02DC	$0875			MOVF	STACK_4+1, 0
$02DD	$00C2			MOVWF	_vdelay_ms_local_numberofcyc+1
$02DE	$0876			MOVF	STACK_4+2, 0
$02DF	$00C3			MOVWF	_vdelay_ms_local_numberofcyc+2
$02E0	$0877			MOVF	STACK_4+3, 0
$02E1	$00C4			MOVWF	_vdelay_ms_local_numberofcyc+3
;delays.pbas,73 :: 		NumberOfCyc = NumberOfCyc >> 5  ' Dec and While below take around 32 instructions
$02E2	$3005			MOVLW	5
$02E3	$00F0			MOVWF	STACK_0
$02E4	$0874			MOVF	STACK_4, 0
$02E5	$00C1			MOVWF	_vdelay_ms_local_numberofcyc
$02E6	$0875			MOVF	STACK_4+1, 0
$02E7	$00C2			MOVWF	_vdelay_ms_local_numberofcyc+1
$02E8	$0876			MOVF	STACK_4+2, 0
$02E9	$00C3			MOVWF	_vdelay_ms_local_numberofcyc+2
$02EA	$0877			MOVF	STACK_4+3, 0
$02EB	$00C4			MOVWF	_vdelay_ms_local_numberofcyc+3
$02EC	$0870			MOVF	STACK_0, 0
$02ED	$	L_VDelay_ms_1:
$02ED	$1903			BTFSC	STATUS, Z
$02EE	$2AF6			GOTO	L_VDelay_ms_2
$02EF	$0CC4			RRF	_vdelay_ms_local_numberofcyc+3, 1
$02F0	$0CC3			RRF	_vdelay_ms_local_numberofcyc+2, 1
$02F1	$0CC2			RRF	_vdelay_ms_local_numberofcyc+1, 1
$02F2	$0CC1			RRF	_vdelay_ms_local_numberofcyc, 1
$02F3	$13C4			BCF	_vdelay_ms_local_numberofcyc+3, 7
$02F4	$3FFF			ADDLW	255
$02F5	$2AED			GOTO	L_VDelay_ms_1
$02F6	$	L_VDelay_ms_2:
;delays.pbas,74 :: 		while ( Lo(NumberOfCyc) or Hi(NumberOfCyc) or Higher(NumberOfCyc) or Highest(NumberOfCyc) ) <> 0
$02F6	$	delays_L_22:
$02F6	$30FF			MOVLW	255
$02F7	$0541			ANDWF	_vdelay_ms_local_numberofcyc, 0
$02F8	$00F8			MOVWF	STACK_8
$02F9	$0842			MOVF	_vdelay_ms_local_numberofcyc+1, 0
$02FA	$00F0			MOVWF	STACK_0
$02FB	$0870			MOVF	STACK_0, 0
$02FC	$04F8			IORWF	STACK_8, 1
$02FD	$0843			MOVF	_vdelay_ms_local_numberofcyc+2, 0
$02FE	$00F0			MOVWF	STACK_0
$02FF	$0844			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$0300	$00F1			MOVWF	STACK_0+1
$0301	$0870			MOVF	STACK_0, 0
$0302	$04F8			IORWF	STACK_8, 1
$0303	$0844			MOVF	_vdelay_ms_local_numberofcyc+3, 0
$0304	$00F0			MOVWF	STACK_0
$0305	$0870			MOVF	STACK_0, 0
$0306	$0478			IORWF	STACK_8, 0
$0307	$00F4			MOVWF	STACK_4
$0308	$0874			MOVF	STACK_4, 0
$0309	$3A00			XORLW	0
$030A	$1903			BTFSC	STATUS, Z
$030B	$2B15			GOTO	delays_L_23
;delays.pbas,75 :: 		Dec(NumberOfCyc)
$030C	$3001			MOVLW	1
$030D	$02C1			SUBWF	_vdelay_ms_local_numberofcyc, 1
$030E	$1C03			BTFSS	STATUS, C
$030F	$02C2			SUBWF	_vdelay_ms_local_numberofcyc+1, 1
$0310	$1C03			BTFSS	STATUS, C
$0311	$02C3			SUBWF	_vdelay_ms_local_numberofcyc+2, 1
$0312	$1C03			BTFSS	STATUS, C
$0313	$02C4			SUBWF	_vdelay_ms_local_numberofcyc+3, 1
$0314	$2AF6			GOTO	delays_L_22
$0315	$	delays_L_23:
;delays.pbas,76 :: 		wend
$0315	$	delays_L_17:
$0315	$0008			RETURN
$03C4	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$03C4	$1303			BCF	STATUS, RP1
$03C5	$1283			BCF	STATUS, RP0
$03C6	$01B4			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$03C7	$01B5			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$03C8	$01B8			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$03C9	$0833			MOVF	FARG_Usart_Read_Text+1, 0
$03CA	$0084			MOVWF	FSR
$03CB	$0800			MOVF	INDF, 0
$03CC	$00B7			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$03CD	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$03CD	$24F4			CALL	_usart_data_ready
$03CE	$0870			MOVF	STACK_0, 0
$03CF	$3A00			XORLW	0
$03D0	$1903			BTFSC	STATUS, Z
$03D1	$2BFD			GOTO	USART_b75_L_34
$03D2	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$03D2	$24C1			CALL	_usart_read
$03D3	$0870			MOVF	STACK_0, 0
$03D4	$00B6			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$03D5	$0834			MOVF	_usart_read_text_local_i, 0
$03D6	$0732			ADDWF	FARG_Usart_Read_Text, 0
$03D7	$00F1			MOVWF	STACK_1
$03D8	$0871			MOVF	STACK_1, 0
$03D9	$0084			MOVWF	FSR
$03DA	$0871			MOVF	STACK_1, 0
$03DB	$0084			MOVWF	FSR
$03DC	$0870			MOVF	STACK_0, 0
$03DD	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$03DE	$0836			MOVF	_usart_read_text_local_data, 0
$03DF	$0637			XORWF	_usart_read_text_local_data2, 0
$03E0	$1D03			BTFSS	STATUS, Z
$03E1	$2BE7			GOTO	USART_b75_L_37
$03E2	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$03E2	$0835			MOVF	_usart_read_text_local_j, 0
$03E3	$0234			SUBWF	_usart_read_text_local_i, 0
$03E4	$00B8			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$03E5	$0AB5			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$03E6	$2BE9			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$03E7	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$03E7	$01B5			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$03E8	$01B8			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$03E9	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$03E9	$0835			MOVF	_usart_read_text_local_j, 0
$03EA	$0733			ADDWF	FARG_Usart_Read_Text+1, 0
$03EB	$0084			MOVWF	FSR
$03EC	$0800			MOVF	INDF, 0
$03ED	$00F1			MOVWF	STACK_1
$03EE	$0871			MOVF	STACK_1, 0
$03EF	$00B7			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$03F0	$0871			MOVF	STACK_1, 0
$03F1	$3A00			XORLW	0
$03F2	$1D03			BTFSS	STATUS, Z
$03F3	$2BF5			GOTO	USART_b75_L_40
$03F4	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$03F4	$2BFE			GOTO	USART_b75_L_30
$03F5	$	USART_b75_L_40:
$03F5	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$03F5	$0AB4			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$03F6	$0834			MOVF	_usart_read_text_local_i, 0
$03F7	$3C14			SUBLW	20
$03F8	$1803			BTFSC	STATUS, C
$03F9	$2BFD			GOTO	USART_b75_L_43
$03FA	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$03FA	$3013			MOVLW	19
$03FB	$00B8			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$03FC	$2BFE			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$03FD	$	USART_b75_L_43:
$03FD	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$03FD	$	USART_b75_L_34:
$03FD	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$03FD	$2BCD			GOTO	USART_b75_L_29
$03FE	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$03FE	$0838			MOVF	_usart_read_text_local_lasti, 0
$03FF	$0732			ADDWF	FARG_Usart_Read_Text, 0
$0400	$00F0			MOVWF	STACK_0
$0401	$0870			MOVF	STACK_0, 0
$0402	$0084			MOVWF	FSR
$0403	$0870			MOVF	STACK_0, 0
$0404	$0084			MOVWF	FSR
$0405	$0180			CLRF	INDF, 1
$0406	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$0406	$0008			RETURN
$0496	$	_usart_write_text:
;USART_b75.ppas,121 :: 		
;USART_b75.ppas,122 :: 		
$0496	$1303			BCF	STATUS, RP1
$0497	$1283			BCF	STATUS, RP0
$0498	$01B3			CLRF	_usart_write_text_local_i, 1
;USART_b75.ppas,123 :: 		
$0499	$0832			MOVF	FARG_Usart_Write_Text, 0
$049A	$0084			MOVWF	FSR
$049B	$0800			MOVF	INDF, 0
$049C	$00B4			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,124 :: 		
$049D	$	USART_b75_L_47:
$049D	$0834			MOVF	_usart_write_text_local_data, 0
$049E	$3A00			XORLW	0
$049F	$1903			BTFSC	STATUS, Z
$04A0	$2CAB			GOTO	USART_b75_L_48
;USART_b75.ppas,126 :: 		
$04A1	$0834			MOVF	_usart_write_text_local_data, 0
$04A2	$00BF			MOVWF	FARG_USART_Write
$04A3	$24D4			CALL	_usart_write
;USART_b75.ppas,127 :: 		
$04A4	$0AB3			INCF	_usart_write_text_local_i, 1
;USART_b75.ppas,128 :: 		
$04A5	$0833			MOVF	_usart_write_text_local_i, 0
$04A6	$0732			ADDWF	FARG_Usart_Write_Text, 0
$04A7	$0084			MOVWF	FSR
$04A8	$0800			MOVF	INDF, 0
$04A9	$00B4			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,129 :: 		
$04AA	$2C9D			GOTO	USART_b75_L_47
$04AB	$	USART_b75_L_48:
$04AB	$	USART_b75_L_45:
;USART_b75.ppas,130 :: 		
$04AB	$0008			RETURN
$0132	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$0132	$1303			BCF	STATUS, RP1
$0133	$1283			BCF	STATUS, RP0
$0134	$01B3			CLRF	_strtoint_local_result
$0135	$01B4			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$0136	$3010			MOVLW	16
$0137	$00B7			MOVWF	_strtoint_local_ep
$0138	$3027			MOVLW	39
$0139	$00B8			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$013A	$01B5			CLRF	_strtoint_local_i
$013B	$01B6			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$013C	$01BB			CLRF	_strtoint_local_tmp
$013D	$01BC			CLRF	_strtoint_local_tmp+1
$013E	$01BD			CLRF	_strtoint_local_tmp+2
$013F	$01BE			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$0140	$01B9			CLRF	_strtoint_local_negative
$0141	$01BA			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$0142	$	conv_L_172:
$0142	$0835			MOVF	_strtoint_local_i, 0
$0143	$0732			ADDWF	FARG_StrToInt, 0
$0144	$0084			MOVWF	FSR
$0145	$0800			MOVF	INDF, 0
$0146	$00F4			MOVWF	STACK_4
$0147	$0874			MOVF	STACK_4, 0
$0148	$3A00			XORLW	0
$0149	$1903			BTFSC	STATUS, Z
$014A	$29AE			GOTO	conv_L_173
;conv.ppas,355 :: 		
$014B	$0835			MOVF	_strtoint_local_i, 0
$014C	$0732			ADDWF	FARG_StrToInt, 0
$014D	$0084			MOVWF	FSR
$014E	$0800			MOVF	INDF, 0
$014F	$00F4			MOVWF	STACK_4
$0150	$0874			MOVF	STACK_4, 0
$0151	$3A2D			XORLW	45
$0152	$1D03			BTFSS	STATUS, Z
$0153	$295B			GOTO	conv_L_177
$0154	$	conv_L_176:
;conv.ppas,357 :: 		
$0154	$30FF			MOVLW	255
$0155	$00B9			MOVWF	_strtoint_local_negative
$0156	$01BA			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$0157	$0AB5			INCF	_strtoint_local_i, 1
$0158	$1903			BTFSC	STATUS, Z
$0159	$0AB6			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$015A	$2942			GOTO	conv_L_172
;conv.ppas,360 :: 		
$015B	$	conv_L_177:
$015B	$	conv_L_178:
;conv.ppas,361 :: 		
$015B	$0835			MOVF	_strtoint_local_i, 0
$015C	$0732			ADDWF	FARG_StrToInt, 0
$015D	$0084			MOVWF	FSR
$015E	$0800			MOVF	INDF, 0
$015F	$00F4			MOVWF	STACK_4
$0160	$0874			MOVF	STACK_4, 0
$0161	$3A20			XORLW	32
$0162	$1903			BTFSC	STATUS, Z
$0163	$299E			GOTO	conv_L_180
$0164	$	conv_L_179:
;conv.ppas,362 :: 		
$0164	$0835			MOVF	_strtoint_local_i, 0
$0165	$0732			ADDWF	FARG_StrToInt, 0
$0166	$0084			MOVWF	FSR
$0167	$0800			MOVF	INDF, 0
$0168	$00F0			MOVWF	STACK_0
$0169	$3030			MOVLW	48
$016A	$00F8			MOVWF	STACK_8
$016B	$01F9			CLRF	STACK_8+1
$016C	$01FA			CLRF	STACK_8+2
$016D	$01FB			CLRF	STACK_8+3
$016E	$0870			MOVF	STACK_0, 0
$016F	$00F4			MOVWF	STACK_4
$0170	$01F5			CLRF	STACK_4+1
$0171	$01F6			CLRF	STACK_4+2
$0172	$01F7			CLRF	STACK_4+3
$0173	$0874			MOVF	STACK_4, 0
$0174	$00F0			MOVWF	STACK_0
$0175	$0875			MOVF	STACK_4+1, 0
$0176	$00F1			MOVWF	STACK_0+1
$0177	$0876			MOVF	STACK_4+2, 0
$0178	$00F2			MOVWF	STACK_0+2
$0179	$0877			MOVF	STACK_4+3, 0
$017A	$00F3			MOVWF	STACK_0+3
$017B	$0878			MOVF	STACK_8, 0
$017C	$02F0			SUBWF	STACK_0, 1
$017D	$0879			MOVF	STACK_8+1, 0
$017E	$1C03			BTFSS	STATUS, C
$017F	$0F79			INCFSZ	STACK_8+1, 0
$0180	$02F1			SUBWF	STACK_0+1, 1
$0181	$087A			MOVF	STACK_8+2, 0
$0182	$1C03			BTFSS	STATUS, C
$0183	$0F7A			INCFSZ	STACK_8+2, 0
$0184	$02F2			SUBWF	STACK_0+2, 1
$0185	$087B			MOVF	STACK_8+3, 0
$0186	$1C03			BTFSS	STATUS, C
$0187	$0F7B			INCFSZ	STACK_8+3, 0
$0188	$02F3			SUBWF	STACK_0+3, 1
$0189	$0837			MOVF	_strtoint_local_ep, 0
$018A	$00F4			MOVWF	STACK_4
$018B	$0838			MOVF	_strtoint_local_ep+1, 0
$018C	$00F5			MOVWF	STACK_4+1
$018D	$01F6			CLRF	STACK_4+2
$018E	$01F7			CLRF	STACK_4+3
$018F	$2407			CALL	_mul_32x32_s
$0190	$0870			MOVF	STACK_0, 0
$0191	$07BB			ADDWF	_strtoint_local_tmp, 1
$0192	$0871			MOVF	STACK_0+1, 0
$0193	$1803			BTFSC	STATUS, C
$0194	$0F71			INCFSZ	STACK_0+1, 0
$0195	$07BC			ADDWF	_strtoint_local_tmp+1, 1
$0196	$0872			MOVF	STACK_0+2, 0
$0197	$1803			BTFSC	STATUS, C
$0198	$0F72			INCFSZ	STACK_0+2, 0
$0199	$07BD			ADDWF	_strtoint_local_tmp+2, 1
$019A	$0873			MOVF	STACK_0+3, 0
$019B	$1803			BTFSC	STATUS, C
$019C	$0F73			INCFSZ	STACK_0+3, 0
$019D	$07BE			ADDWF	_strtoint_local_tmp+3, 1
$019E	$	conv_L_180:
$019E	$	conv_L_181:
;conv.ppas,363 :: 		
$019E	$300A			MOVLW	10
$019F	$00F4			MOVWF	STACK_4
$01A0	$01F5			CLRF	STACK_4+1
$01A1	$0837			MOVF	_strtoint_local_ep, 0
$01A2	$00F0			MOVWF	STACK_0
$01A3	$0838			MOVF	_strtoint_local_ep+1, 0
$01A4	$00F1			MOVWF	STACK_0+1
$01A5	$2479			CALL	_div_16x16_u
$01A6	$0870			MOVF	STACK_0, 0
$01A7	$00B7			MOVWF	_strtoint_local_ep
$01A8	$0871			MOVF	STACK_0+1, 0
$01A9	$00B8			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$01AA	$0AB5			INCF	_strtoint_local_i, 1
$01AB	$1903			BTFSC	STATUS, Z
$01AC	$0AB6			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$01AD	$2942			GOTO	conv_L_172
$01AE	$	conv_L_173:
;conv.ppas,370 :: 		
$01AE	$0839			MOVF	_strtoint_local_negative, 0
$01AF	$043A			IORWF	_strtoint_local_negative+1, 0
$01B0	$1903			BTFSC	STATUS, Z
$01B1	$29B6			GOTO	conv_L_183
$01B2	$	conv_L_182:
$01B2	$3006			MOVLW	6
$01B3	$00B7			MOVWF	_strtoint_local_ep
$01B4	$01B8			CLRF	_strtoint_local_ep+1
$01B5	$29B9			GOTO	conv_L_184
;conv.ppas,371 :: 		
$01B6	$	conv_L_183:
$01B6	$3005			MOVLW	5
$01B7	$00B7			MOVWF	_strtoint_local_ep
$01B8	$01B8			CLRF	_strtoint_local_ep+1
$01B9	$	conv_L_184:
;conv.ppas,373 :: 		
$01B9	$	conv_L_186:
$01B9	$0836			MOVF	_strtoint_local_i+1, 0
$01BA	$0638			XORWF	_strtoint_local_ep+1, 0
$01BB	$1D03			BTFSS	STATUS, Z
$01BC	$29BF			GOTO	L_StrToInt_20
$01BD	$0837			MOVF	_strtoint_local_ep, 0
$01BE	$0635			XORWF	_strtoint_local_i, 0
$01BF	$	L_StrToInt_20:
$01BF	$1903			BTFSC	STATUS, Z
$01C0	$29DB			GOTO	conv_L_187
;conv.ppas,375 :: 		
$01C1	$300A			MOVLW	10
$01C2	$00F4			MOVWF	STACK_4
$01C3	$01F5			CLRF	STACK_4+1
$01C4	$01F6			CLRF	STACK_4+2
$01C5	$01F7			CLRF	STACK_4+3
$01C6	$083B			MOVF	_strtoint_local_tmp, 0
$01C7	$00F0			MOVWF	STACK_0
$01C8	$083C			MOVF	_strtoint_local_tmp+1, 0
$01C9	$00F1			MOVWF	STACK_0+1
$01CA	$083D			MOVF	_strtoint_local_tmp+2, 0
$01CB	$00F2			MOVWF	STACK_0+2
$01CC	$083E			MOVF	_strtoint_local_tmp+3, 0
$01CD	$00F3			MOVWF	STACK_0+3
$01CE	$21F4			CALL	_div_32x32_s
$01CF	$0870			MOVF	STACK_0, 0
$01D0	$00BB			MOVWF	_strtoint_local_tmp
$01D1	$0871			MOVF	STACK_0+1, 0
$01D2	$00BC			MOVWF	_strtoint_local_tmp+1
$01D3	$0872			MOVF	STACK_0+2, 0
$01D4	$00BD			MOVWF	_strtoint_local_tmp+2
$01D5	$0873			MOVF	STACK_0+3, 0
$01D6	$00BE			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$01D7	$0AB5			INCF	_strtoint_local_i, 1
$01D8	$1903			BTFSC	STATUS, Z
$01D9	$0AB6			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$01DA	$29B9			GOTO	conv_L_186
$01DB	$	conv_L_187:
;conv.ppas,380 :: 		
$01DB	$083B			MOVF	_strtoint_local_tmp, 0
$01DC	$00B3			MOVWF	_strtoint_local_result
$01DD	$083C			MOVF	_strtoint_local_tmp+1, 0
$01DE	$00B4			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$01DF	$3000			MOVLW	0
$01E0	$063A			XORWF	_strtoint_local_negative+1, 0
$01E1	$1D03			BTFSS	STATUS, Z
$01E2	$29E5			GOTO	L_StrToInt_21
$01E3	$30FF			MOVLW	255
$01E4	$0639			XORWF	_strtoint_local_negative, 0
$01E5	$	L_StrToInt_21:
$01E5	$1D03			BTFSS	STATUS, Z
$01E6	$29EF			GOTO	conv_L_191
$01E7	$	conv_L_190:
;conv.ppas,383 :: 		
$01E7	$0833			MOVF	_strtoint_local_result, 0
$01E8	$3C00			SUBLW	0
$01E9	$00B3			MOVWF	_strtoint_local_result
$01EA	$0834			MOVF	_strtoint_local_result+1, 0
$01EB	$1C03			BTFSS	STATUS, C
$01EC	$3F01			ADDLW	1
$01ED	$01B4			CLRF	_strtoint_local_result+1
$01EE	$02B4			SUBWF	_strtoint_local_result+1, 1
$01EF	$	conv_L_191:
$01EF	$	conv_L_192:
$01EF	$	conv_L_170:
;conv.ppas,384 :: 		
$01EF	$0833			MOVF	_strtoint_local_result, 0
$01F0	$00F0			MOVWF	STACK_0
$01F1	$0834			MOVF	_strtoint_local_result+1, 0
$01F2	$00F1			MOVWF	STACK_0+1
$01F3	$0008			RETURN
$036E	$	_ciclo:
;ControleSerial.pbas,15 :: 		dim x as integer 'Controle do laço
;ControleSerial.pbas,19 :: 		if direcao=true then PORTC.1=1 delay_ms(10) PORTC.1=0 direcao=false end if
$036E	$1303			BCF	STATUS, RP1
$036F	$1283			BCF	STATUS, RP0
$0370	$0821			MOVF	_direcao, 0
$0371	$3AFF			XORLW	255
$0372	$1D03			BTFSS	STATUS, Z
$0373	$2B86			GOTO	ControleSerial_L_2
$0374	$	ControleSerial_L_1:
$0374	$	ControleSerial_L_4:
$0374	$1487			BSF	PORTC, 1
$0375	$	ControleSerial_L_5:
$0375	$300D			MOVLW	13
$0376	$00FB			MOVWF	STACK_11
$0377	$30FF			MOVLW	255
$0378	$00FA			MOVWF	STACK_10
$0379	$0BFB			DECFSZ	STACK_11, F
$037A	$2B7C			GOTO	$+2
$037B	$2B7F			GOTO	$+4
$037C	$0BFA			DECFSZ	STACK_10, F
$037D	$2B7C			GOTO	$-1
$037E	$2B79			GOTO	$-5
$037F	$30F3			MOVLW	243
$0380	$00FA			MOVWF	STACK_10
$0381	$0BFA			DECFSZ	STACK_10, F
$0382	$2B81			GOTO	$-1
$0383	$0000			NOP
$0384	$1087			BCF	PORTC, 1
$0385	$	ControleSerial_L_7:
$0385	$01A1			CLRF	_direcao, 1
$0386	$	ControleSerial_L_2:
$0386	$	ControleSerial_L_3:
;ControleSerial.pbas,23 :: 		if passo=true then PORTC.2=1 delay_ms(10) PORTC.2=0 passo=false end if
$0386	$0822			MOVF	_passo, 0
$0387	$3AFF			XORLW	255
$0388	$1D03			BTFSS	STATUS, Z
$0389	$2B9C			GOTO	ControleSerial_L_9
$038A	$	ControleSerial_L_8:
$038A	$	ControleSerial_L_11:
$038A	$1507			BSF	PORTC, 2
$038B	$	ControleSerial_L_12:
$038B	$300D			MOVLW	13
$038C	$00FB			MOVWF	STACK_11
$038D	$30FF			MOVLW	255
$038E	$00FA			MOVWF	STACK_10
$038F	$0BFB			DECFSZ	STACK_11, F
$0390	$2B92			GOTO	$+2
$0391	$2B95			GOTO	$+4
$0392	$0BFA			DECFSZ	STACK_10, F
$0393	$2B92			GOTO	$-1
$0394	$2B8F			GOTO	$-5
$0395	$30F3			MOVLW	243
$0396	$00FA			MOVWF	STACK_10
$0397	$0BFA			DECFSZ	STACK_10, F
$0398	$2B97			GOTO	$-1
$0399	$0000			NOP
$039A	$1107			BCF	PORTC, 2
$039B	$	ControleSerial_L_14:
$039B	$01A2			CLRF	_passo, 1
$039C	$	ControleSerial_L_9:
$039C	$	ControleSerial_L_10:
;ControleSerial.pbas,28 :: 		for x=1 to cl step 1
$039C	$3001			MOVLW	1
$039D	$00B4			MOVWF	_ciclo_local_x
$039E	$01B5			CLRF	_ciclo_local_x+1
$039F	$	ControleSerial_L_15:
$039F	$3080			MOVLW	128
$03A0	$0633			XORWF	FARG_ciclo+1, 0
$03A1	$00F0			MOVWF	STACK_0
$03A2	$3080			MOVLW	128
$03A3	$0635			XORWF	_ciclo_local_x+1, 0
$03A4	$0270			SUBWF	STACK_0, 0
$03A5	$1D03			BTFSS	STATUS, Z
$03A6	$2BA9			GOTO	L_ciclo_0
$03A7	$0834			MOVF	_ciclo_local_x, 0
$03A8	$0232			SUBWF	FARG_ciclo, 0
$03A9	$	L_ciclo_0:
$03A9	$1C03			BTFSS	STATUS, C
$03AA	$2BC3			GOTO	ControleSerial_L_18
;ControleSerial.pbas,29 :: 		PORTC.0=1
$03AB	$	ControleSerial_L_19:
$03AB	$1407			BSF	PORTC, 0
$03AC	$	ControleSerial_L_20:
;ControleSerial.pbas,30 :: 		vdelay_ms(tmpOn)
$03AC	$0823			MOVF	_tmpon, 0
$03AD	$00BF			MOVWF	FARG_VDelay_ms
$03AE	$0824			MOVF	_tmpon+1, 0
$03AF	$00C0			MOVWF	FARG_VDelay_ms+1
$03B0	$228E			CALL	_vdelay_ms
;ControleSerial.pbas,31 :: 		PORTC.0=0
$03B1	$1007			BCF	PORTC, 0
$03B2	$	ControleSerial_L_22:
;ControleSerial.pbas,32 :: 		vdelay_ms(tmpOff)
$03B2	$0825			MOVF	_tmpoff, 0
$03B3	$00BF			MOVWF	FARG_VDelay_ms
$03B4	$0826			MOVF	_tmpoff+1, 0
$03B5	$00C0			MOVWF	FARG_VDelay_ms+1
$03B6	$228E			CALL	_vdelay_ms
;ControleSerial.pbas,33 :: 		next x
$03B7	$0835			MOVF	_ciclo_local_x+1, 0
$03B8	$0633			XORWF	FARG_ciclo+1, 0
$03B9	$1D03			BTFSS	STATUS, Z
$03BA	$2BBD			GOTO	L_ciclo_1
$03BB	$0832			MOVF	FARG_ciclo, 0
$03BC	$0634			XORWF	_ciclo_local_x, 0
$03BD	$	L_ciclo_1:
$03BD	$1903			BTFSC	STATUS, Z
$03BE	$2BC3			GOTO	ControleSerial_L_18
$03BF	$	ControleSerial_L_16:
$03BF	$0AB4			INCF	_ciclo_local_x, 1
$03C0	$1903			BTFSC	STATUS, Z
$03C1	$0AB5			INCF	_ciclo_local_x+1, 1
$03C2	$2B9F			GOTO	ControleSerial_L_15
$03C3	$	ControleSerial_L_18:
$03C3	$	ControleSerial_L_0:
$03C3	$0008			RETURN
$04AC	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$04AC	$	USART_b75_L_1:
$04AC	$1303			BCF	STATUS, RP1
$04AD	$1683			BSF	STATUS, RP0
$04AE	$1698			BSF	TXSTA, 5
$04AF	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$04AF	$3090			MOVLW	144
$04B0	$1283			BCF	STATUS, RP0
$04B1	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$04B2	$	USART_b75_L_3:
$04B2	$1683			BSF	STATUS, RP0
$04B3	$1686			BSF	TRISB, 5
$04B4	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$04B4	$	USART_b75_L_5:
$04B4	$1786			BSF	TRISB, 7
$04B5	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$04B5	$	USART_b75_L_8:
$04B5	$1283			BCF	STATUS, RP0
$04B6	$080C			MOVF	PIR1, 0
$04B7	$00F1			MOVWF	STACK_1
$04B8	$3000			MOVLW	0
$04B9	$1AF1			BTFSC	STACK_1, 5
$04BA	$3001			MOVLW	1
$04BB	$00F1			MOVWF	STACK_1
$04BC	$0871			MOVF	STACK_1, 0
$04BD	$3A01			XORLW	1
$04BE	$1903			BTFSC	STATUS, Z
$04BF	$2CB5			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$04C0	$	USART_b75_L_9:
$04C0	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$04C0	$0008			RETURN
$0316	$	_main:
;ControleSerial.pbas,37 :: 		main:
$0316	$	_main_main:
;ControleSerial.pbas,38 :: 		TRISA=%11111111
$0316	$30FF			MOVLW	255
$0317	$1303			BCF	STATUS, RP1
$0318	$1683			BSF	STATUS, RP0
$0319	$0085			MOVWF	TRISA
;ControleSerial.pbas,39 :: 		TRISB=%01111111
$031A	$307F			MOVLW	127
$031B	$0086			MOVWF	TRISB
;ControleSerial.pbas,40 :: 		TRISC=%00000000
$031C	$0187			CLRF	TRISC, 1
;ControleSerial.pbas,41 :: 		INTCON=%00000000
$031D	$018B			CLRF	INTCON, 1
;ControleSerial.pbas,42 :: 		ANSEL=%00000000
$031E	$1703			BSF	STATUS, RP1
$031F	$1283			BCF	STATUS, RP0
$0320	$019E			CLRF	ANSEL, 1
;ControleSerial.pbas,43 :: 		ANSELH=%00000000
$0321	$019F			CLRF	ANSELH, 1
;ControleSerial.pbas,45 :: 		PORTC=0
$0322	$1303			BCF	STATUS, RP1
$0323	$0187			CLRF	PORTC, 1
;ControleSerial.pbas,46 :: 		Usart_Init(9600)
$0324	$3019			MOVLW	25
$0325	$1683			BSF	STATUS, RP0
$0326	$0099			MOVWF	SPBRG
$0327	$1518			BSF	TXSTA, BRGH
$0328	$24AC			CALL	_usart_init
;ControleSerial.pbas,47 :: 		tmpOn=25       ' Colocar 25 para usar no simulador.
$0329	$3019			MOVLW	25
$032A	$00A3			MOVWF	_tmpon
$032B	$01A4			CLRF	_tmpon+1
;ControleSerial.pbas,48 :: 		tmpOff=25
$032C	$3019			MOVLW	25
$032D	$00A5			MOVWF	_tmpoff
$032E	$01A6			CLRF	_tmpoff+1
;ControleSerial.pbas,49 :: 		direcao=false   ' Inicia em sentido horário
$032F	$01A1			CLRF	_direcao, 1
;ControleSerial.pbas,50 :: 		passo=false     ' Inicia em passos de 3.75
$0330	$01A2			CLRF	_passo, 1
;ControleSerial.pbas,52 :: 		executa:
$0331	$	_main_executa:
;ControleSerial.pbas,56 :: 		if Usart_Data_Ready() then
$0331	$24F4			CALL	_usart_data_ready
$0332	$0870			MOVF	STACK_0, 0
$0333	$1903			BTFSC	STATUS, Z
$0334	$2B6C			GOTO	ControleSerial_L_25
$0335	$	ControleSerial_L_24:
;ControleSerial.pbas,57 :: 		Usart_Read_Text(recebe,"/") 'Recebe o valor até que chegue /
$0335	$3027			MOVLW	_recebe
$0336	$00B2			MOVWF	FARG_Usart_Read_Text
$0337	$302F			MOVLW	47
$0338	$00B0			MOVWF	?main_Local_Text+0
$0339	$01B1			CLRF	?main_Local_Text+1
$033A	$3030			MOVLW	?main_Local_Text
$033B	$00B3			MOVWF	FARG_Usart_Read_Text+1
$033C	$23C4			CALL	_usart_read_text
;ControleSerial.pbas,58 :: 		Usart_Write_Text(recebe)
$033D	$3027			MOVLW	_recebe
$033E	$00B2			MOVWF	FARG_Usart_Write_Text
$033F	$2496			CALL	_usart_write_text
;ControleSerial.pbas,59 :: 		valor=StrToInt(recebe)
$0340	$3027			MOVLW	_recebe
$0341	$00B2			MOVWF	FARG_StrToInt
$0342	$2132			CALL	_strtoint
$0343	$0870			MOVF	STACK_0, 0
$0344	$00AE			MOVWF	_valor
$0345	$0871			MOVF	STACK_0+1, 0
$0346	$00AF			MOVWF	_valor+1
;ControleSerial.pbas,60 :: 		if valor<1000 then ciclo(valor) end if 'Envia o número de pulsos.
$0347	$3080			MOVLW	128
$0348	$0671			XORWF	STACK_0+1, 0
$0349	$00F2			MOVWF	STACK_2
$034A	$3080			MOVLW	128
$034B	$3A03			XORLW	3
$034C	$0272			SUBWF	STACK_2, 0
$034D	$1D03			BTFSS	STATUS, Z
$034E	$2B51			GOTO	L_main_2
$034F	$30E8			MOVLW	232
$0350	$0270			SUBWF	STACK_0, 0
$0351	$	L_main_2:
$0351	$1803			BTFSC	STATUS, C
$0352	$2B58			GOTO	ControleSerial_L_28
$0353	$	ControleSerial_L_27:
$0353	$082E			MOVF	_valor, 0
$0354	$00B2			MOVWF	FARG_ciclo
$0355	$082F			MOVF	_valor+1, 0
$0356	$00B3			MOVWF	FARG_ciclo+1
$0357	$236E			CALL	_ciclo
$0358	$	ControleSerial_L_28:
$0358	$	ControleSerial_L_29:
;ControleSerial.pbas,61 :: 		if valor=1000 then direcao=true end if 'Determina a mudança de direção.
$0358	$082F			MOVF	_valor+1, 0
$0359	$3A03			XORLW	3
$035A	$1D03			BTFSS	STATUS, Z
$035B	$2B5E			GOTO	L_main_3
$035C	$30E8			MOVLW	232
$035D	$062E			XORWF	_valor, 0
$035E	$	L_main_3:
$035E	$1D03			BTFSS	STATUS, Z
$035F	$2B62			GOTO	ControleSerial_L_31
$0360	$	ControleSerial_L_30:
$0360	$30FF			MOVLW	255
$0361	$00A1			MOVWF	_direcao
$0362	$	ControleSerial_L_31:
$0362	$	ControleSerial_L_32:
;ControleSerial.pbas,62 :: 		if valor=1002 then passo=true end if   'Determina a mudança de passo.
$0362	$082F			MOVF	_valor+1, 0
$0363	$3A03			XORLW	3
$0364	$1D03			BTFSS	STATUS, Z
$0365	$2B68			GOTO	L_main_4
$0366	$30EA			MOVLW	234
$0367	$062E			XORWF	_valor, 0
$0368	$	L_main_4:
$0368	$1D03			BTFSS	STATUS, Z
$0369	$2B6C			GOTO	ControleSerial_L_34
$036A	$	ControleSerial_L_33:
$036A	$30FF			MOVLW	255
$036B	$00A2			MOVWF	_passo
$036C	$	ControleSerial_L_34:
$036C	$	ControleSerial_L_35:
$036C	$	ControleSerial_L_25:
;ControleSerial.pbas,63 :: 		end if
$036C	$	ControleSerial_L_26:
;ControleSerial.pbas,64 :: 		goto executa
$036C	$2B31			GOTO	_main_executa
$036D	$2B6D			GOTO	$
