;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 12/11/2020 22:42:32
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$28DA			GOTO	_main
$0004	$	_pulso:
;ControleMotor.pbas,13 :: 		sub procedure pulso()
;ControleMotor.pbas,14 :: 		if revolucao = true then
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$0820			MOVF	_revolucao, 0
$0007	$3AFF			XORLW	255
$0008	$1D03			BTFSS	STATUS, Z
$0009	$2886			GOTO	ControleMotor_L_2
$000A	$	ControleMotor_L_1:
;ControleMotor.pbas,15 :: 		if direcao = false then
$000A	$0821			MOVF	_direcao, 0
$000B	$3A00			XORLW	0
$000C	$1D03			BTFSS	STATUS, Z
$000D	$281F			GOTO	ControleMotor_L_5
$000E	$	ControleMotor_L_4:
;ControleMotor.pbas,16 :: 		inc(passo)
$000E	$0AA2			INCF	_passo, 1
$000F	$1903			BTFSC	STATUS, Z
$0010	$0AA3			INCF	_passo+1, 1
;ControleMotor.pbas,17 :: 		if passo > 8 then passo=1 end if
$0011	$3080			MOVLW	128
$0012	$00F0			MOVWF	STACK_0
$0013	$3080			MOVLW	128
$0014	$0623			XORWF	_passo+1, 0
$0015	$0270			SUBWF	STACK_0, 0
$0016	$1D03			BTFSS	STATUS, Z
$0017	$281A			GOTO	L_pulso_0
$0018	$0822			MOVF	_passo, 0
$0019	$3C08			SUBLW	8
$001A	$	L_pulso_0:
$001A	$1803			BTFSC	STATUS, C
$001B	$281F			GOTO	ControleMotor_L_8
$001C	$	ControleMotor_L_7:
$001C	$3001			MOVLW	1
$001D	$00A2			MOVWF	_passo
$001E	$01A3			CLRF	_passo+1
$001F	$	ControleMotor_L_8:
$001F	$	ControleMotor_L_9:
$001F	$	ControleMotor_L_5:
;ControleMotor.pbas,18 :: 		end if
$001F	$	ControleMotor_L_6:
;ControleMotor.pbas,19 :: 		if direcao = true then
$001F	$0821			MOVF	_direcao, 0
$0020	$3AFF			XORLW	255
$0021	$1D03			BTFSS	STATUS, Z
$0022	$2835			GOTO	ControleMotor_L_11
$0023	$	ControleMotor_L_10:
;ControleMotor.pbas,20 :: 		dec(passo)
$0023	$3001			MOVLW	1
$0024	$02A2			SUBWF	_passo, 1
$0025	$1C03			BTFSS	STATUS, C
$0026	$03A3			DECF	_passo+1, 1
;ControleMotor.pbas,21 :: 		if passo < 1 then passo=8 end if
$0027	$3080			MOVLW	128
$0028	$0623			XORWF	_passo+1, 0
$0029	$00F0			MOVWF	STACK_0
$002A	$3080			MOVLW	128
$002B	$0270			SUBWF	STACK_0, 0
$002C	$1D03			BTFSS	STATUS, Z
$002D	$2830			GOTO	L_pulso_1
$002E	$3001			MOVLW	1
$002F	$0222			SUBWF	_passo, 0
$0030	$	L_pulso_1:
$0030	$1803			BTFSC	STATUS, C
$0031	$2835			GOTO	ControleMotor_L_14
$0032	$	ControleMotor_L_13:
$0032	$3008			MOVLW	8
$0033	$00A2			MOVWF	_passo
$0034	$01A3			CLRF	_passo+1
$0035	$	ControleMotor_L_14:
$0035	$	ControleMotor_L_15:
$0035	$	ControleMotor_L_11:
;ControleMotor.pbas,22 :: 		end if
$0035	$	ControleMotor_L_12:
;ControleMotor.pbas,23 :: 		if passo=1 then PORTC=%00001001 end if
$0035	$3000			MOVLW	0
$0036	$0623			XORWF	_passo+1, 0
$0037	$1D03			BTFSS	STATUS, Z
$0038	$283B			GOTO	L_pulso_2
$0039	$3001			MOVLW	1
$003A	$0622			XORWF	_passo, 0
$003B	$	L_pulso_2:
$003B	$1D03			BTFSS	STATUS, Z
$003C	$283F			GOTO	ControleMotor_L_17
$003D	$	ControleMotor_L_16:
$003D	$3009			MOVLW	9
$003E	$0087			MOVWF	PORTC
$003F	$	ControleMotor_L_17:
$003F	$	ControleMotor_L_18:
;ControleMotor.pbas,24 :: 		if passo=2 then PORTC=%00001000 end if
$003F	$3000			MOVLW	0
$0040	$0623			XORWF	_passo+1, 0
$0041	$1D03			BTFSS	STATUS, Z
$0042	$2845			GOTO	L_pulso_3
$0043	$3002			MOVLW	2
$0044	$0622			XORWF	_passo, 0
$0045	$	L_pulso_3:
$0045	$1D03			BTFSS	STATUS, Z
$0046	$2849			GOTO	ControleMotor_L_20
$0047	$	ControleMotor_L_19:
$0047	$3008			MOVLW	8
$0048	$0087			MOVWF	PORTC
$0049	$	ControleMotor_L_20:
$0049	$	ControleMotor_L_21:
;ControleMotor.pbas,25 :: 		if passo=3 then PORTC=%00001100 end if
$0049	$3000			MOVLW	0
$004A	$0623			XORWF	_passo+1, 0
$004B	$1D03			BTFSS	STATUS, Z
$004C	$284F			GOTO	L_pulso_4
$004D	$3003			MOVLW	3
$004E	$0622			XORWF	_passo, 0
$004F	$	L_pulso_4:
$004F	$1D03			BTFSS	STATUS, Z
$0050	$2853			GOTO	ControleMotor_L_23
$0051	$	ControleMotor_L_22:
$0051	$300C			MOVLW	12
$0052	$0087			MOVWF	PORTC
$0053	$	ControleMotor_L_23:
$0053	$	ControleMotor_L_24:
;ControleMotor.pbas,26 :: 		if passo=4 then PORTC=%00000100 end if
$0053	$3000			MOVLW	0
$0054	$0623			XORWF	_passo+1, 0
$0055	$1D03			BTFSS	STATUS, Z
$0056	$2859			GOTO	L_pulso_5
$0057	$3004			MOVLW	4
$0058	$0622			XORWF	_passo, 0
$0059	$	L_pulso_5:
$0059	$1D03			BTFSS	STATUS, Z
$005A	$285D			GOTO	ControleMotor_L_26
$005B	$	ControleMotor_L_25:
$005B	$3004			MOVLW	4
$005C	$0087			MOVWF	PORTC
$005D	$	ControleMotor_L_26:
$005D	$	ControleMotor_L_27:
;ControleMotor.pbas,27 :: 		if passo=5 then PORTC=%00000110 end if
$005D	$3000			MOVLW	0
$005E	$0623			XORWF	_passo+1, 0
$005F	$1D03			BTFSS	STATUS, Z
$0060	$2863			GOTO	L_pulso_6
$0061	$3005			MOVLW	5
$0062	$0622			XORWF	_passo, 0
$0063	$	L_pulso_6:
$0063	$1D03			BTFSS	STATUS, Z
$0064	$2867			GOTO	ControleMotor_L_29
$0065	$	ControleMotor_L_28:
$0065	$3006			MOVLW	6
$0066	$0087			MOVWF	PORTC
$0067	$	ControleMotor_L_29:
$0067	$	ControleMotor_L_30:
;ControleMotor.pbas,28 :: 		if passo=6 then PORTC=%00000010 end if
$0067	$3000			MOVLW	0
$0068	$0623			XORWF	_passo+1, 0
$0069	$1D03			BTFSS	STATUS, Z
$006A	$286D			GOTO	L_pulso_7
$006B	$3006			MOVLW	6
$006C	$0622			XORWF	_passo, 0
$006D	$	L_pulso_7:
$006D	$1D03			BTFSS	STATUS, Z
$006E	$2871			GOTO	ControleMotor_L_32
$006F	$	ControleMotor_L_31:
$006F	$3002			MOVLW	2
$0070	$0087			MOVWF	PORTC
$0071	$	ControleMotor_L_32:
$0071	$	ControleMotor_L_33:
;ControleMotor.pbas,29 :: 		if passo=7 then PORTC=%00000011 end if
$0071	$3000			MOVLW	0
$0072	$0623			XORWF	_passo+1, 0
$0073	$1D03			BTFSS	STATUS, Z
$0074	$2877			GOTO	L_pulso_8
$0075	$3007			MOVLW	7
$0076	$0622			XORWF	_passo, 0
$0077	$	L_pulso_8:
$0077	$1D03			BTFSS	STATUS, Z
$0078	$287B			GOTO	ControleMotor_L_35
$0079	$	ControleMotor_L_34:
$0079	$3003			MOVLW	3
$007A	$0087			MOVWF	PORTC
$007B	$	ControleMotor_L_35:
$007B	$	ControleMotor_L_36:
;ControleMotor.pbas,30 :: 		if passo=8 then PORTC=%00000001 end if
$007B	$3000			MOVLW	0
$007C	$0623			XORWF	_passo+1, 0
$007D	$1D03			BTFSS	STATUS, Z
$007E	$2881			GOTO	L_pulso_9
$007F	$3008			MOVLW	8
$0080	$0622			XORWF	_passo, 0
$0081	$	L_pulso_9:
$0081	$1D03			BTFSS	STATUS, Z
$0082	$2885			GOTO	ControleMotor_L_38
$0083	$	ControleMotor_L_37:
$0083	$3001			MOVLW	1
$0084	$0087			MOVWF	PORTC
$0085	$	ControleMotor_L_38:
$0085	$	ControleMotor_L_39:
$0085	$28D9			GOTO	ControleMotor_L_3
;ControleMotor.pbas,31 :: 		else
$0086	$	ControleMotor_L_2:
;ControleMotor.pbas,32 :: 		if direcao = false then
$0086	$0821			MOVF	_direcao, 0
$0087	$3A00			XORLW	0
$0088	$1D03			BTFSS	STATUS, Z
$0089	$289B			GOTO	ControleMotor_L_41
$008A	$	ControleMotor_L_40:
;ControleMotor.pbas,33 :: 		inc(passo)
$008A	$0AA2			INCF	_passo, 1
$008B	$1903			BTFSC	STATUS, Z
$008C	$0AA3			INCF	_passo+1, 1
;ControleMotor.pbas,34 :: 		if passo > 4 then passo=1 end if
$008D	$3080			MOVLW	128
$008E	$00F0			MOVWF	STACK_0
$008F	$3080			MOVLW	128
$0090	$0623			XORWF	_passo+1, 0
$0091	$0270			SUBWF	STACK_0, 0
$0092	$1D03			BTFSS	STATUS, Z
$0093	$2896			GOTO	L_pulso_10
$0094	$0822			MOVF	_passo, 0
$0095	$3C04			SUBLW	4
$0096	$	L_pulso_10:
$0096	$1803			BTFSC	STATUS, C
$0097	$289B			GOTO	ControleMotor_L_44
$0098	$	ControleMotor_L_43:
$0098	$3001			MOVLW	1
$0099	$00A2			MOVWF	_passo
$009A	$01A3			CLRF	_passo+1
$009B	$	ControleMotor_L_44:
$009B	$	ControleMotor_L_45:
$009B	$	ControleMotor_L_41:
;ControleMotor.pbas,35 :: 		end if
$009B	$	ControleMotor_L_42:
;ControleMotor.pbas,36 :: 		if direcao = true then
$009B	$0821			MOVF	_direcao, 0
$009C	$3AFF			XORLW	255
$009D	$1D03			BTFSS	STATUS, Z
$009E	$28B1			GOTO	ControleMotor_L_47
$009F	$	ControleMotor_L_46:
;ControleMotor.pbas,37 :: 		dec(passo)
$009F	$3001			MOVLW	1
$00A0	$02A2			SUBWF	_passo, 1
$00A1	$1C03			BTFSS	STATUS, C
$00A2	$03A3			DECF	_passo+1, 1
;ControleMotor.pbas,38 :: 		if passo < 1 then passo=4 end if
$00A3	$3080			MOVLW	128
$00A4	$0623			XORWF	_passo+1, 0
$00A5	$00F0			MOVWF	STACK_0
$00A6	$3080			MOVLW	128
$00A7	$0270			SUBWF	STACK_0, 0
$00A8	$1D03			BTFSS	STATUS, Z
$00A9	$28AC			GOTO	L_pulso_11
$00AA	$3001			MOVLW	1
$00AB	$0222			SUBWF	_passo, 0
$00AC	$	L_pulso_11:
$00AC	$1803			BTFSC	STATUS, C
$00AD	$28B1			GOTO	ControleMotor_L_50
$00AE	$	ControleMotor_L_49:
$00AE	$3004			MOVLW	4
$00AF	$00A2			MOVWF	_passo
$00B0	$01A3			CLRF	_passo+1
$00B1	$	ControleMotor_L_50:
$00B1	$	ControleMotor_L_51:
$00B1	$	ControleMotor_L_47:
;ControleMotor.pbas,39 :: 		end if
$00B1	$	ControleMotor_L_48:
;ControleMotor.pbas,40 :: 		if passo=1 then PORTC=%00001000 end if
$00B1	$3000			MOVLW	0
$00B2	$0623			XORWF	_passo+1, 0
$00B3	$1D03			BTFSS	STATUS, Z
$00B4	$28B7			GOTO	L_pulso_12
$00B5	$3001			MOVLW	1
$00B6	$0622			XORWF	_passo, 0
$00B7	$	L_pulso_12:
$00B7	$1D03			BTFSS	STATUS, Z
$00B8	$28BB			GOTO	ControleMotor_L_53
$00B9	$	ControleMotor_L_52:
$00B9	$3008			MOVLW	8
$00BA	$0087			MOVWF	PORTC
$00BB	$	ControleMotor_L_53:
$00BB	$	ControleMotor_L_54:
;ControleMotor.pbas,41 :: 		if passo=2 then PORTC=%00000100 end if
$00BB	$3000			MOVLW	0
$00BC	$0623			XORWF	_passo+1, 0
$00BD	$1D03			BTFSS	STATUS, Z
$00BE	$28C1			GOTO	L_pulso_13
$00BF	$3002			MOVLW	2
$00C0	$0622			XORWF	_passo, 0
$00C1	$	L_pulso_13:
$00C1	$1D03			BTFSS	STATUS, Z
$00C2	$28C5			GOTO	ControleMotor_L_56
$00C3	$	ControleMotor_L_55:
$00C3	$3004			MOVLW	4
$00C4	$0087			MOVWF	PORTC
$00C5	$	ControleMotor_L_56:
$00C5	$	ControleMotor_L_57:
;ControleMotor.pbas,42 :: 		if passo=3 then PORTC=%00000010 end if
$00C5	$3000			MOVLW	0
$00C6	$0623			XORWF	_passo+1, 0
$00C7	$1D03			BTFSS	STATUS, Z
$00C8	$28CB			GOTO	L_pulso_14
$00C9	$3003			MOVLW	3
$00CA	$0622			XORWF	_passo, 0
$00CB	$	L_pulso_14:
$00CB	$1D03			BTFSS	STATUS, Z
$00CC	$28CF			GOTO	ControleMotor_L_59
$00CD	$	ControleMotor_L_58:
$00CD	$3002			MOVLW	2
$00CE	$0087			MOVWF	PORTC
$00CF	$	ControleMotor_L_59:
$00CF	$	ControleMotor_L_60:
;ControleMotor.pbas,43 :: 		if passo=4 then PORTC=%00000001 end if
$00CF	$3000			MOVLW	0
$00D0	$0623			XORWF	_passo+1, 0
$00D1	$1D03			BTFSS	STATUS, Z
$00D2	$28D5			GOTO	L_pulso_15
$00D3	$3004			MOVLW	4
$00D4	$0622			XORWF	_passo, 0
$00D5	$	L_pulso_15:
$00D5	$1D03			BTFSS	STATUS, Z
$00D6	$28D9			GOTO	ControleMotor_L_62
$00D7	$	ControleMotor_L_61:
$00D7	$3001			MOVLW	1
$00D8	$0087			MOVWF	PORTC
$00D9	$	ControleMotor_L_62:
$00D9	$	ControleMotor_L_63:
;ControleMotor.pbas,44 :: 		end if
$00D9	$	ControleMotor_L_3:
$00D9	$	ControleMotor_L_0:
$00D9	$0008			RETURN
$00DA	$	_main:
;ControleMotor.pbas,47 :: 		main:
$00DA	$	_main_main:
;ControleMotor.pbas,48 :: 		TRISA=%11111111
$00DA	$30FF			MOVLW	255
$00DB	$1303			BCF	STATUS, RP1
$00DC	$1683			BSF	STATUS, RP0
$00DD	$0085			MOVWF	TRISA
;ControleMotor.pbas,49 :: 		TRISB=%01111111
$00DE	$307F			MOVLW	127
$00DF	$0086			MOVWF	TRISB
;ControleMotor.pbas,50 :: 		TRISC=%00000000
$00E0	$0187			CLRF	TRISC, 1
;ControleMotor.pbas,51 :: 		INTCON=%00000000
$00E1	$018B			CLRF	INTCON, 1
;ControleMotor.pbas,52 :: 		ANSEL=%00000000
$00E2	$1703			BSF	STATUS, RP1
$00E3	$1283			BCF	STATUS, RP0
$00E4	$019E			CLRF	ANSEL, 1
;ControleMotor.pbas,53 :: 		ANSELH=%00000000
$00E5	$019F			CLRF	ANSELH, 1
;ControleMotor.pbas,55 :: 		PORTC=0
$00E6	$1303			BCF	STATUS, RP1
$00E7	$0187			CLRF	PORTC, 1
;ControleMotor.pbas,56 :: 		passo=0
$00E8	$01A2			CLRF	_passo
$00E9	$01A3			CLRF	_passo+1
;ControleMotor.pbas,57 :: 		borda=false
$00EA	$01A4			CLRF	_borda, 1
;ControleMotor.pbas,58 :: 		borda2=false
$00EB	$01A5			CLRF	_borda2, 1
;ControleMotor.pbas,59 :: 		borda3=false
$00EC	$01A6			CLRF	_borda3, 1
;ControleMotor.pbas,60 :: 		borda4=false
$00ED	$01A7			CLRF	_borda4, 1
;ControleMotor.pbas,61 :: 		direcao=true
$00EE	$30FF			MOVLW	255
$00EF	$00A1			MOVWF	_direcao
;ControleMotor.pbas,62 :: 		revolucao=true 'Quando true 400 pulsos por revolução
$00F0	$30FF			MOVLW	255
$00F1	$00A0			MOVWF	_revolucao
;ControleMotor.pbas,65 :: 		executa:
$00F2	$	_main_executa:
;ControleMotor.pbas,69 :: 		if testbit(porta,0)=1 then
$00F2	$3001			MOVLW	1
$00F3	$0505			ANDWF	PORTA, 0
$00F4	$00F1			MOVWF	STACK_1
$00F5	$0871			MOVF	STACK_1, 0
$00F6	$3A01			XORLW	1
$00F7	$1D03			BTFSS	STATUS, Z
$00F8	$2900			GOTO	ControleMotor_L_66
$00F9	$	ControleMotor_L_65:
;ControleMotor.pbas,70 :: 		if borda=false then
$00F9	$0824			MOVF	_borda, 0
$00FA	$3A00			XORLW	0
$00FB	$1D03			BTFSS	STATUS, Z
$00FC	$2900			GOTO	ControleMotor_L_69
$00FD	$	ControleMotor_L_68:
;ControleMotor.pbas,71 :: 		borda=true
$00FD	$30FF			MOVLW	255
$00FE	$00A4			MOVWF	_borda
;ControleMotor.pbas,72 :: 		pulso()
$00FF	$2004			CALL	_pulso
$0100	$	ControleMotor_L_69:
;ControleMotor.pbas,73 :: 		end if
$0100	$	ControleMotor_L_70:
$0100	$	ControleMotor_L_66:
;ControleMotor.pbas,74 :: 		end if
$0100	$	ControleMotor_L_67:
;ControleMotor.pbas,75 :: 		if testbit(porta,0)=0 then borda=false end if
$0100	$3001			MOVLW	1
$0101	$0505			ANDWF	PORTA, 0
$0102	$00F1			MOVWF	STACK_1
$0103	$0871			MOVF	STACK_1, 0
$0104	$3A00			XORLW	0
$0105	$1D03			BTFSS	STATUS, Z
$0106	$2908			GOTO	ControleMotor_L_72
$0107	$	ControleMotor_L_71:
$0107	$01A4			CLRF	_borda, 1
$0108	$	ControleMotor_L_72:
$0108	$	ControleMotor_L_73:
;ControleMotor.pbas,77 :: 		if testbit(porta,1)=1 then
$0108	$3000			MOVLW	0
$0109	$1885			BTFSC	PORTA, 1
$010A	$3001			MOVLW	1
$010B	$00F1			MOVWF	STACK_1
$010C	$0871			MOVF	STACK_1, 0
$010D	$3A01			XORLW	1
$010E	$1D03			BTFSS	STATUS, Z
$010F	$2917			GOTO	ControleMotor_L_75
$0110	$	ControleMotor_L_74:
;ControleMotor.pbas,78 :: 		if borda2=false then
$0110	$0825			MOVF	_borda2, 0
$0111	$3A00			XORLW	0
$0112	$1D03			BTFSS	STATUS, Z
$0113	$2917			GOTO	ControleMotor_L_78
$0114	$	ControleMotor_L_77:
;ControleMotor.pbas,79 :: 		borda2=true
$0114	$30FF			MOVLW	255
$0115	$00A5			MOVWF	_borda2
;ControleMotor.pbas,80 :: 		pulso()
$0116	$2004			CALL	_pulso
$0117	$	ControleMotor_L_78:
;ControleMotor.pbas,81 :: 		end if
$0117	$	ControleMotor_L_79:
$0117	$	ControleMotor_L_75:
;ControleMotor.pbas,82 :: 		end if
$0117	$	ControleMotor_L_76:
;ControleMotor.pbas,83 :: 		if testbit(porta,0)=0 then borda2=false end if
$0117	$3001			MOVLW	1
$0118	$0505			ANDWF	PORTA, 0
$0119	$00F1			MOVWF	STACK_1
$011A	$0871			MOVF	STACK_1, 0
$011B	$3A00			XORLW	0
$011C	$1D03			BTFSS	STATUS, Z
$011D	$291F			GOTO	ControleMotor_L_81
$011E	$	ControleMotor_L_80:
$011E	$01A5			CLRF	_borda2, 1
$011F	$	ControleMotor_L_81:
$011F	$	ControleMotor_L_82:
;ControleMotor.pbas,88 :: 		if testbit(porta,2)=1 then
$011F	$3000			MOVLW	0
$0120	$1905			BTFSC	PORTA, 2
$0121	$3001			MOVLW	1
$0122	$00F1			MOVWF	STACK_1
$0123	$0871			MOVF	STACK_1, 0
$0124	$3A01			XORLW	1
$0125	$1D03			BTFSS	STATUS, Z
$0126	$2935			GOTO	ControleMotor_L_84
$0127	$	ControleMotor_L_83:
;ControleMotor.pbas,89 :: 		if borda3=false then
$0127	$0826			MOVF	_borda3, 0
$0128	$3A00			XORLW	0
$0129	$1D03			BTFSS	STATUS, Z
$012A	$2935			GOTO	ControleMotor_L_87
$012B	$	ControleMotor_L_86:
;ControleMotor.pbas,90 :: 		borda3=true
$012B	$30FF			MOVLW	255
$012C	$00A6			MOVWF	_borda3
;ControleMotor.pbas,91 :: 		if direcao = false then direcao=true else direcao=false end if
$012D	$0821			MOVF	_direcao, 0
$012E	$3A00			XORLW	0
$012F	$1D03			BTFSS	STATUS, Z
$0130	$2934			GOTO	ControleMotor_L_90
$0131	$	ControleMotor_L_89:
$0131	$30FF			MOVLW	255
$0132	$00A1			MOVWF	_direcao
$0133	$2935			GOTO	ControleMotor_L_91
$0134	$	ControleMotor_L_90:
$0134	$01A1			CLRF	_direcao, 1
$0135	$	ControleMotor_L_91:
$0135	$	ControleMotor_L_87:
;ControleMotor.pbas,92 :: 		end if
$0135	$	ControleMotor_L_88:
$0135	$	ControleMotor_L_84:
;ControleMotor.pbas,93 :: 		end if
$0135	$	ControleMotor_L_85:
;ControleMotor.pbas,94 :: 		if testbit(porta,1)=0 then borda2=false end if
$0135	$3000			MOVLW	0
$0136	$1885			BTFSC	PORTA, 1
$0137	$3001			MOVLW	1
$0138	$00F1			MOVWF	STACK_1
$0139	$0871			MOVF	STACK_1, 0
$013A	$3A00			XORLW	0
$013B	$1D03			BTFSS	STATUS, Z
$013C	$293E			GOTO	ControleMotor_L_93
$013D	$	ControleMotor_L_92:
$013D	$01A5			CLRF	_borda2, 1
$013E	$	ControleMotor_L_93:
$013E	$	ControleMotor_L_94:
;ControleMotor.pbas,99 :: 		if testbit(porta,3)=1 then
$013E	$3000			MOVLW	0
$013F	$1985			BTFSC	PORTA, 3
$0140	$3001			MOVLW	1
$0141	$00F1			MOVWF	STACK_1
$0142	$0871			MOVF	STACK_1, 0
$0143	$3A01			XORLW	1
$0144	$1D03			BTFSS	STATUS, Z
$0145	$2962			GOTO	ControleMotor_L_96
$0146	$	ControleMotor_L_95:
;ControleMotor.pbas,100 :: 		if borda4=false then
$0146	$0827			MOVF	_borda4, 0
$0147	$3A00			XORLW	0
$0148	$1D03			BTFSS	STATUS, Z
$0149	$2962			GOTO	ControleMotor_L_99
$014A	$	ControleMotor_L_98:
;ControleMotor.pbas,101 :: 		borda4=true
$014A	$30FF			MOVLW	255
$014B	$00A7			MOVWF	_borda4
;ControleMotor.pbas,102 :: 		if revolucao=false then
$014C	$0820			MOVF	_revolucao, 0
$014D	$3A00			XORLW	0
$014E	$1D03			BTFSS	STATUS, Z
$014F	$2953			GOTO	ControleMotor_L_102
$0150	$	ControleMotor_L_101:
;ControleMotor.pbas,103 :: 		revolucao = true
$0150	$30FF			MOVLW	255
$0151	$00A0			MOVWF	_revolucao
$0152	$2962			GOTO	ControleMotor_L_103
;ControleMotor.pbas,104 :: 		else
$0153	$	ControleMotor_L_102:
;ControleMotor.pbas,105 :: 		revolucao=false
$0153	$01A0			CLRF	_revolucao, 1
;ControleMotor.pbas,106 :: 		if passo > 4 then passo=4 end if
$0154	$3080			MOVLW	128
$0155	$00F0			MOVWF	STACK_0
$0156	$3080			MOVLW	128
$0157	$0623			XORWF	_passo+1, 0
$0158	$0270			SUBWF	STACK_0, 0
$0159	$1D03			BTFSS	STATUS, Z
$015A	$295D			GOTO	L_main_16
$015B	$0822			MOVF	_passo, 0
$015C	$3C04			SUBLW	4
$015D	$	L_main_16:
$015D	$1803			BTFSC	STATUS, C
$015E	$2962			GOTO	ControleMotor_L_105
$015F	$	ControleMotor_L_104:
$015F	$3004			MOVLW	4
$0160	$00A2			MOVWF	_passo
$0161	$01A3			CLRF	_passo+1
$0162	$	ControleMotor_L_105:
$0162	$	ControleMotor_L_106:
;ControleMotor.pbas,107 :: 		end if
$0162	$	ControleMotor_L_103:
$0162	$	ControleMotor_L_99:
;ControleMotor.pbas,108 :: 		end if
$0162	$	ControleMotor_L_100:
$0162	$	ControleMotor_L_96:
;ControleMotor.pbas,109 :: 		end if
$0162	$	ControleMotor_L_97:
;ControleMotor.pbas,110 :: 		if testbit(porta,2)=0 then borda4=false end if
$0162	$3000			MOVLW	0
$0163	$1905			BTFSC	PORTA, 2
$0164	$3001			MOVLW	1
$0165	$00F1			MOVWF	STACK_1
$0166	$0871			MOVF	STACK_1, 0
$0167	$3A00			XORLW	0
$0168	$1D03			BTFSS	STATUS, Z
$0169	$296B			GOTO	ControleMotor_L_108
$016A	$	ControleMotor_L_107:
$016A	$01A7			CLRF	_borda4, 1
$016B	$	ControleMotor_L_108:
$016B	$	ControleMotor_L_109:
;ControleMotor.pbas,117 :: 		goto executa
$016B	$28F2			GOTO	_main_executa
$016C	$296C			GOTO	$
